window.ENGINE_CONTENT = {
 parts:[
  {id:'inlet',name:'Inlet',zh:'进气口',category:'01 · WELCOME, AIR',en:'Air enters the engine here.',translation:'空气从这里进入发动机。',action:'Find the big opening at the front.',actionZh:'转到正面，找到前方的大圆口。',detail:'The inlet guides air toward the fan.',detailZh:'进气口把空气引向风扇。'},
  {id:'fan',name:'Fan',zh:'风扇',category:'02 · MOVING AIR',en:'The fan moves air toward the back of the engine.',translation:'风扇让空气向发动机后方流动。',action:'Press play. Watch the fan turn.',actionZh:'按播放或走一小步，观察风扇转动。',detail:'Much of the air goes around the core. Some air enters the core.',detailZh:'许多空气绕过核心流动，另一部分空气进入核心。'},
  {id:'bypass',name:'Bypass duct',zh:'外涵道',category:'03 · THE OUTER ROUTE',en:'This air travels around the engine core.',translation:'这里的空气绕着发动机核心流动。',action:'Open the shell. Follow the blue outer route.',actionZh:'打开发动机外壳，选择“外涵道”，按播放或走一小步追踪蓝色路线。',detail:'Bypass air does not pass through the combustor. It helps push the airplane forward.',detailZh:'外涵道的空气不经过燃烧室，它也帮助推动飞机向前。'},
  {id:'compressor',name:'Compressor',zh:'压气机',category:'04 · SQUEEZING AIR',en:'The compressor squeezes air before it reaches the combustor.',translation:'压气机在空气进入燃烧室前将它压缩。',action:'Look for several rows of small blades.',actionZh:'打开外壳，找一找风扇后方的多排小叶片。',detail:'Rows of rotating and fixed blades work together to raise the air pressure.',detailZh:'转动叶片和固定叶片共同工作，让空气的压力升高。'},
  {id:'combustor',name:'Combustor',zh:'燃烧室',category:'05 · ADDING ENERGY',en:'Fuel mixes with air and burns here.',translation:'燃料在这里与空气混合并燃烧。',action:'Follow the core route. Where does its color change?',actionZh:'选择“核心”路线，按播放或走一小步，观察空气在哪里变成暖色。',detail:'Burning fuel adds energy. The hot gas flows toward the turbine.',detailZh:'燃料燃烧增加能量，热气体继续流向涡轮。暖色表示加热，颜色并非空气的真实颜色。'},
  {id:'turbine',name:'Turbine',zh:'涡轮',category:'06 · TURNING TOGETHER',en:'Hot gas turns the turbine.',translation:'热气体推动涡轮转动。',action:'Highlight the shaft. Watch what turns together.',actionZh:'突出转轴连接，按播放或走一小步，观察哪些零件一起转动。',detail:'The turbine turns a shaft that drives blades farther forward.',detailZh:'涡轮带动轴转动，把动力传给前面的旋转部件。'},
  {id:'shaft',name:'Shaft',zh:'转轴',category:'07 · A HIDDEN CONNECTION',en:'A shaft carries turning motion between parts.',translation:'转轴在零件之间传递旋转运动。',action:'Highlight the shaft and take one slow step.',actionZh:'点击“突出转轴连接”，再按“走一小步”。',detail:'This model uses one shaft to show the connection. Real engines can have more than one shaft.',detailZh:'模型用一根轴表示连接关系。实际发动机可以有多根同心轴，分别连接不同的旋转部件。'},
  {id:'nozzle',name:'Nozzle',zh:'喷口',category:'08 · ON YOUR WAY',en:'Gas leaves the engine through the nozzle.',translation:'气体从喷口离开发动机。',action:'Follow the air all the way to the back.',actionZh:'观察气流从前方进入、向后排出的完整过程。',detail:'The engine pushes air backward. The air pushes the engine forward.',detailZh:'发动机把空气向后推，空气也给发动机向前的推力。'}
 ],
 tasks:[
  {id:'find',title:'找到大风扇',short:'01 · 找一找',instruction:'选择 Fan，按播放或走一小步，观察前方的叶片。',question:'Which part moves lots of air?',zh:'哪个部件让许多空气动起来？',needs:['spin'],found:'fan',answers:[['fan','Fan','风扇'],['nozzle','Nozzle','喷口']],correct:'fan',hint:'看看前方转动的大叶片。喷口在后方，是气体离开的地方。',discovery:'大风扇让空气向后流动。',discoveryEn:'The fan moves air backward.'},
  {id:'routes',title:'空气的两条路',short:'02 · 跟一跟',instruction:'打开外壳，分别选择“外涵道”和“核心”，各按一次播放或走一小步。',question:'Which route goes around the combustor?',zh:'哪条路线绕过燃烧室？',needs:['open','bypass','core'],answers:[['bypass','Bypass route','外涵道路线'],['core','Core route','核心路线']],correct:'bypass',hint:'核心路线经过燃烧室。再看看外侧的蓝色路线，它绕着核心走。',discovery:'外涵空气绕过核心，不经过燃烧室。',discoveryEn:'Bypass air goes around the core.'},
  {id:'connect',title:'谁把它们连起来？',short:'03 · 动一动',instruction:'打开外壳，突出转轴连接，再播放或走一小步，观察前后部件。',question:'What carries the turning motion?',zh:'什么在传递旋转运动？',needs:['open','shaft'],answers:[['shell','Outer shell','外壳'],['shaft','Shaft','转轴']],correct:'shaft',hint:'外壳没有跟着转动。找一找穿过发动机中心的细长连接。',discovery:'转轴把涡轮的旋转传给前面的部件。',discoveryEn:'A shaft carries turning motion.'},
  {id:'fuel',title:'能量从哪里来？',short:'04 · 讲一讲',instruction:'打开外壳，选择 Combustor，读一读或听一听介绍，再观察核心路线。',question:'Where is fuel added and burned?',zh:'燃料在哪里加入并燃烧？',needs:['open','core'],found:'combustor',answers:[['bypass','Bypass duct','外涵道'],['combustor','Combustor','燃烧室']],correct:'combustor',hint:'外涵空气绕过核心。找到核心内让空气变成暖色的区域。',discovery:'燃料在燃烧室燃烧，为核心气流增加能量。',discoveryEn:'Fuel burns in the combustor.'}
 ]
};
