/* Original bilingual story. See SOURCES.md for science review and illustration notes. */
window.BOOK = {id:'cloud',title:'Where Do Clouds Travel?',titleZh:'云朵去哪里旅行',subtitle:'Didi and the promise of rain',subtitleZh:'滴滴与一场雨的约定',age:'5 岁起 · 亲子共读',coverImg:'assets/00-cover.webp',audioDir:'audio'};
window.PAGES = [
 {title:'云朵去哪里旅行',titleEn:'Where Do Clouds Travel?',act:0,img:'assets/00-cover.webp',cover:true,
  zh:'池塘里住着一滴爱问问题的水，叫滴滴。每天，它都望着天上的云：“你们有时候像小船，有时候像高山。你们到底要去哪里？”这一天，一场意想不到的旅行，把滴滴带进了答案里。',
  en:'Didi was a curious little drop in a pond. Every day, Didi watched the clouds. “Sometimes you look like boats. Sometimes you look like mountains. Where are you going?” One day, an unexpected journey carried Didi right into the answer.',
  why:'这是真实的水循环，加上一点想象',whyEn:'Real science, with a little imagination',
  factZh:'滴滴会说话、会想家，是故事里的想象。真实的小水滴没有眼睛，也不会选择目的地。我们会跟着它，观察水怎样在天空、地面和植物之间移动。图中放大的水滴帮助我们看清，大小不代表真实比例。',
  factEn:'Talking and feeling homesick belong to our story. Real water drops have no eyes and cannot choose a destination. The enlarged drops help us follow water; they are not drawn to scale.',
  qZh:'你想跟滴滴先去哪里？',qEn:'Where would you like to go with Didi?',choicesZh:['到云里面看看','沿着小溪走走'],choicesEn:['Inside a cloud','Along a stream'],answer:-1,feedbackZh:'都可以！这趟旅行会带我们发现天空和地面怎样连在一起。',feedbackEn:'Both are wonderful choices. Our journey connects the sky and the ground.'},
 {title:'留在岸边的约定',titleEn:'A Promise by the Pond',act:1,img:'assets/01-promise.webp',
  zh:'好些天没有下雨了。阿跳的荷叶离岸边越来越远，小柳树也低下了头。“水都躲到哪里去了？”阿跳问。滴滴看了看水面上的阳光：“我去找找。要是遇见云，我就问问雨的消息！”可它连第一步该怎么走，都不知道。',
  en:'It had not rained for days. Frog’s lily pad was farther from the bank, and the young willow drooped. “Where is our water hiding?” asked Frog. “I will find out,” said Didi. “If I meet a cloud, I will ask about rain!” But Didi had no idea how to begin.',
  why:'池塘的水为什么会变少？',whyEn:'Why can a pond shrink?',
  factZh:'水会从表面慢慢变成水蒸气，进入空气，这叫蒸发。水也可能渗进泥土，或被植物吸收。池塘水位同时受下雨、流入和流出的水影响，所以不能只用“今天很热”解释所有变化。',
  factEn:'Water can evaporate into the air, soak into soil, or enter plants. Rain and streams can add water. A pond’s level depends on water coming in and going out, not just on how hot today is.',
  qZh:'水少了，一定是被动物喝光了吗？',qEn:'Must animals have drunk all the missing water?',choicesZh:['一定是','还可能去了空气和土里'],choicesEn:['Yes, all of it','It could enter air or soil'],answer:1,feedbackZh:'对，水有好几条去路！看不见，不等于消失。',feedbackEn:'Yes! Water has several routes. Out of sight does not mean gone.'},
 {title:'咦，我怎么不见了？',titleEn:'Where Did I Go?',act:1,img:'assets/02-evaporation.webp',
  zh:'太阳暖暖地照着池塘。慢慢地，滴滴不再是能看见的小水滴了。“阿跳，我还在这里！”它喊。可阿跳只看见清清的空气。滴滴变成了看不见的水蒸气，混进空气里；一股上升的空气，带着它离开了池塘。',
  en:'Sunshine warmed the pond. Slowly, Didi was no longer a visible drop. “Frog, I am still here!” But Frog saw only clear air. Didi had become invisible water vapor and mixed with the air. A rising current carried it away from the pond.',
  why:'水蒸气是白白的烟吗？',whyEn:'Is water vapor white smoke?',
  factZh:'不是。水蒸气是水的气体形态，肉眼看不见；云里可见的白色主要来自许多小水滴或冰晶。蒸发不需要把水烧开，晾着的湿衣服也会变干。太阳提供能量，但不是把水滴用绳子拉上去。',
  factEn:'No. Water vapor is an invisible gas. Visible clouds contain tiny liquid drops or ice crystals. Evaporation does not require boiling: wet clothes can dry in ordinary air. The Sun supplies energy; moving air transports the vapor.',
  qZh:'图里没有画出滴滴，是漏画了吗？',qEn:'Why can you not see Didi in this picture?',choicesZh:['它变成了看不见的水蒸气','它变成了白烟'],choicesEn:['It became invisible vapor','It became white smoke'],answer:0,feedbackZh:'找到了秘密：这页的“看不见”就是科学线索。',feedbackEn:'You found the clue! Being invisible is part of the science.'},
 {title:'云城里的小邻居',titleEn:'Little Neighbors in a Cloud',act:2,img:'assets/03-condensation.webp',
  zh:'越往上，空气越凉。滴滴发现，自己又变成了一颗小水珠！旁边一粒细小的尘埃说：“欢迎，你可以在我身边形成水滴。”四周还有数不清的小水珠。远远看去，它们聚在空气里的样子，就是阿跳看见的那朵白云。',
  en:'Higher up, the air cooled. Didi became a tiny liquid bead again! “Welcome,” said a speck of dust. “A drop can form around me.” Countless little beads surrounded Didi. Seen from far away, all those beads in the air made the white cloud Frog could see.',
  why:'一朵云是怎样出现的？',whyEn:'How does a cloud form?',
  factZh:'含水蒸气的空气冷却到合适条件时，水蒸气会凝结成小水滴，常常围绕细小颗粒形成。很多小水滴一起散射阳光，我们才看见云。更冷的云里还可能有冰晶；云不是一整团水蒸气，也不是棉花。',
  factEn:'When moist air cools enough, vapor condenses into tiny drops, often around airborne particles. Many drops scatter sunlight, making a cloud visible. Colder clouds can also contain ice crystals. A cloud is neither cotton nor a solid piece of vapor.',
  qZh:'白云里能有什么？',qEn:'What can a cloud contain?',choicesZh:['棉花和糖','很多小水滴，也可能有冰晶'],choicesEn:['Cotton and sugar','Tiny drops, sometimes ice crystals'],answer:1,feedbackZh:'正是这样。现在看到的是放大的云中小世界。',feedbackEn:'Exactly. This picture magnifies the tiny world inside a cloud.'},
 {title:'这里没有地板！',titleEn:'There Is No Floor!',act:2,img:'assets/04-floating.webp',
  zh:'“云看起来软软的，可以躺一躺吗？”滴滴刚想坐下，就发现这里根本没有地板。小水珠们散在空气中，轻轻地移动。“我们这么小，落得很慢，”邻居说，“向上流动的空气，还能把我们带起来。”滴滴终于敢朝下面看了一眼。',
  en:'“Could I lie down on this soft cloud?” wondered Didi. But there was no floor! The little beads moved through the air. “We are tiny, so we fall very slowly,” said a neighbor. “Rising air can carry us upward, too.” At last, Didi dared to look down.',
  why:'云为什么没有整团砸下来？',whyEn:'Why does a cloud not fall as one lump?',
  factZh:'云里的水分散成许多很小的水滴或冰晶，并不是一个大水袋。小水滴受到空气阻力，落得很慢；气流也会带动它们。重力一直存在。只有水滴或冰晶长大到足以落下来时，才可能形成降水。',
  factEn:'Cloud water is spread among many tiny drops or crystals, not held in a big bag. Air resistance slows small drops, and air currents move them. Gravity still acts. Drops or crystals must grow enough to fall as precipitation.',
  qZh:'小朋友能站在真正的云上吗？',qEn:'Could you stand on a real cloud?',choicesZh:['不能，它没有地板','能，像床垫一样'],choicesEn:['No, there is no floor','Yes, like a mattress'],answer:0,feedbackZh:'答对了！云看着柔软，却不是能站上去的东西。',feedbackEn:'Right! Looking soft does not mean a cloud can hold you up.'},
 {title:'风把家吹远了',titleEn:'The Wind Carries Us Away',act:2,img:'assets/05-wind.webp',
  zh:'呼——田野像拼图一样，从脚下慢慢滑过。红屋顶变小了，池塘也找不到了。“等等，我答应阿跳要回去！”滴滴着急地喊。风没有转弯。“云不能自己开车，”邻居安慰它，“我们跟着空气走。先看看前面，会遇见什么吧。”',
  en:'Whoosh! Fields slid below like a patchwork quilt. The red roof grew smaller. The pond disappeared. “Wait! I promised Frog I would return!” cried Didi. But the wind kept going. “Clouds cannot steer,” said the neighbor. “We travel with the air. Let us see what comes next.”',
  why:'云是谁推着走的？',whyEn:'What moves a cloud?',
  factZh:'风就是流动的空气，它能搬运水蒸气和云中的小水滴。云的形状还会因为水滴不断形成、蒸发而改变。因此一朵云既在移动，也在变化，并不总是同一群水滴组成的固定“队伍”。',
  factEn:'Wind is moving air. It carries vapor and cloud droplets. A cloud also changes shape as drops form and evaporate. A cloud is not always a fixed group of the very same drops.',
  qZh:'哪样东西能帮我们观察风？',qEn:'What helps us notice the wind?',choicesZh:['飘动的旗子','安静的石头'],choicesEn:['A fluttering flag','A still rock'],answer:0,feedbackZh:'看看旗子朝哪边飘，再看看云。高处和地面的风也可能不同。',feedbackEn:'Watch the flag, then the clouds. Wind higher up may differ from wind near the ground.'},
 {title:'大山挡住了路',titleEn:'A Mountain in the Way',act:3,img:'assets/06-mountain.webp',
  zh:'前面忽然竖起一座大山。“过不去了！”滴滴抱紧身边的伙伴。空气顺着山坡往上爬，带着大家一起升高。更凉的地方，又出现了许多新水珠。云一点点变厚。滴滴突然想到：“伙伴这么多了，我们会不会变成雨？”',
  en:'A mountain rose ahead. “We cannot get through!” cried Didi. The air climbed the slope and carried everyone upward. In the cooler air, more little drops formed. The cloud grew thicker. Didi wondered, “With so many neighbors, could we become rain?”',
  why:'为什么山边常常聚起云？',whyEn:'Why can clouds gather beside mountains?',
  factZh:'潮湿空气遇到山，被迫抬升时会膨胀、冷却。在合适条件下，更多水蒸气凝结，形成云，甚至降雨。不是山“挤破”了云，也不是每次遇山都会下雨：空气中要有足够水分，水滴还要继续长大。',
  factEn:'A mountain can lift moist air. As that air rises, it expands and cools. Under suitable conditions, vapor condenses into clouds and perhaps rain. The mountain does not squeeze a cloud open; enough moisture and drop growth are still needed.',
  qZh:'山坡让这股潮湿空气怎样移动？',qEn:'Which way does the slope make this moist air move?',choicesZh:['往上升','钻进石头里'],choicesEn:['Upward','Inside solid rock'],answer:0,feedbackZh:'对！这一次是大山帮空气升高、冷却。',feedbackEn:'Yes! Here, the mountain helps the air rise and cool.'},
 {title:'云是不是生气了？',titleEn:'Is the Cloud Angry?',act:3,img:'assets/07-dark-cloud.webp',
  zh:'云的下面渐渐暗了。“我们把云弄脏了吗？”滴滴小声问。“没有呀。”一颗小水珠指向头顶，“上面还亮着呢！只是云变厚了，能到达底下的阳光少了。”滴滴松了一口气。原来，灰灰的脸色，并不表示生气。',
  en:'The bottom of the cloud grew darker. “Did we make it dirty?” whispered Didi. “No,” said a little bead. “Look! The top is still bright. Our cloud is thicker, so less sunlight reaches the bottom.” Didi felt better. A gray cloud was not an angry cloud.',
  why:'乌云为什么看起来灰灰的？',whyEn:'Why can a cloud look gray?',
  factZh:'云中的水滴和冰晶会散射光。厚云里的光经过许多次散射，到达底部、再进入我们眼睛的光可能较少，所以底部较暗。灰色本身不是“马上下雨”的保证，还要看云内部的水滴、冰晶和空气条件。',
  factEn:'Drops and ice crystals scatter light. In a thick cloud, less light may reach the base and then our eyes, making it look darker. Gray color alone does not guarantee rain. Conditions inside the cloud matter, too.',
  qZh:'云底变灰，一定是云生气了吗？',qEn:'Does a gray cloud mean the cloud is angry?',choicesZh:['是，它正在发脾气','不是，和光线有关'],choicesEn:['Yes, it is upset','No, it is about light'],answer:1,feedbackZh:'没错。我们可以用光来解释它，不需要猜云的心情。',feedbackEn:'Exactly. Light explains the color; feelings do not.'},
 {title:'一颗雨滴的诞生',titleEn:'Becoming a Raindrop',act:3,img:'assets/08-growing-drops.webp',
  zh:'挤一挤，碰一碰。滴滴遇见了一颗小水珠，两颗合成了更大的一颗；又遇见一颗，它们继续长大。忽然，滴滴感觉自己落得更快了。“我要出发啦！”它和伙伴一起穿过云底。下面，正是那条流向池塘的小溪。',
  en:'Bump, join, grow! Didi met another bead, and the two became one bigger drop. More drops joined. Didi began to fall faster. “Here I go!” Together, they slipped below the cloud. Far below was a stream—the stream that led toward the pond.',
  why:'云里的小水滴怎么变成雨？',whyEn:'How do cloud droplets become rain?',
  factZh:'一些小水滴碰撞、合并，会长成更大的雨滴，落得更快。当它们能穿过气流向下落，并到达地面时，我们就看见雨。冷云里还可能先长出冰晶，落下融化成雨。不是把整朵云倒空；有的水滴途中还会蒸发。',
  factEn:'Some droplets collide and merge into larger drops that fall faster. Rain reaches us when drops fall through the air to the ground. In cold clouds, ice can grow and melt into rain. Some falling drops evaporate before reaching the ground.',
  qZh:'小水珠合并后，通常会怎样？',qEn:'What usually happens when little drops merge?',choicesZh:['变成更大的水滴','变成石头'],choicesEn:['They form a larger drop','They turn into a rock'],answer:0,feedbackZh:'对！雨滴长大了，但云不是一个被戳破的水袋。',feedbackEn:'Yes! Drops grow. A cloud is not a water bag that bursts.'},
 {title:'滴答！第一声回答',titleEn:'Pitter-Patter! An Answer',act:3,img:'assets/09-rain.webp',
  zh:'滴答！滴滴落在一片柳叶上，叶子轻轻一晃，把它送进了泥土。“欢迎回来！”小柳树沙沙地说。远处的阿跳听见雨点，连叫了三声。滴滴也想回答，可泥土里的岔路好多呀：一条向小溪，一条向更深处，还有一条通向树根。',
  en:'Pitter-patter! Didi landed on a willow leaf. The leaf tipped, and Didi slipped into the soil. “Welcome!” rustled the tree. Far away, Frog croaked three times at the sound of rain. Didi wanted to answer, but the soil had many paths: toward the stream, deeper down, and toward the roots.',
  why:'雨落到地面以后都去哪里？',whyEn:'Where does rain go after it lands?',
  factZh:'一部分水沿地面流动，叫径流；一部分渗入土壤；还有一些会留在叶片和水洼上，之后再蒸发。不同地面吸水的速度不同。图中雨滴画得很大是为了讲故事，真实的小雨滴通常接近圆球形，不像长尾巴的眼泪。',
  factEn:'Some water flows over land as runoff. Some soaks into soil. Some stays on leaves or in puddles and later evaporates. Different surfaces absorb water differently. Our enlarged story drops are not to scale; small real raindrops are nearly spherical.',
  qZh:'雨水是不是只有“流进河里”这一条路？',qEn:'Is flowing into a river the only route?',choicesZh:['是，只有一条','不是，还能渗进土里'],choicesEn:['Yes, only one','No, it can soak into soil'],answer:1,feedbackZh:'对，水循环有许多岔路，接下来去地下探险！',feedbackEn:'Right. The water cycle has many branches. Let us explore below ground!'},
 {title:'泥土里的慢慢列车',titleEn:'The Slow Journey Underground',act:4,img:'assets/10-soil.webp',
  zh:'这里没有大隧道，只有土粒和石缝之间的小空隙。滴滴慢慢挤过去，遇见一条蚯蚓。“别急，”蚯蚓说，“有些水会在地下住很久。”滴滴沿着湿湿的细缝前进，忽然看见一根细细的树根。那是小柳树伸来的邀请。',
  en:'There was no grand tunnel—only little spaces between grains and cracks in rock. Didi moved slowly past a worm. “Take your time,” said the worm. “Some water stays underground for a long while.” Along a damp passage, Didi found a fine root: an invitation from the young willow.',
  why:'地下水住在大空洞里吗？',whyEn:'Does groundwater need a big cave?',
  factZh:'很多地下的水藏在土壤、沙粒和岩石的孔隙或裂缝里。土里的水有些被根吸收，有些继续向下补充地下水。地下水也能缓慢流动，之后从泉眼出来，或进入河流。不同水滴的旅程可能长短很不一样。',
  factEn:'Much underground water occupies pores and cracks, not giant caves. Roots take up some soil water; some moves deeper to recharge groundwater. Groundwater can flow slowly and later reach springs or rivers. Different drops can have very different journey times.',
  qZh:'看这张剖面图，水藏在哪里？',qEn:'In this cutaway, where is the water?',choicesZh:['土粒之间的小空隙里','每块石头的正中央'],choicesEn:['In spaces between grains','At the center of every stone'],answer:0,feedbackZh:'找到啦！小空隙连在一起，也能成为水的道路。',feedbackEn:'You found it! Connected small spaces can make a path for water.'},
 {title:'树叶上的秘密出口',titleEn:'A Secret Exit in a Leaf',act:4,img:'assets/11-leaf.webp',
  zh:'滴滴被树根吸收，沿着细小的输水通道来到叶子里。“谢谢你！”小柳树精神起来了。又过了一阵子，滴滴再次变成看不见的水蒸气，从叶片的小气孔离开。“原来，树也和天空相连！”它惊喜地说。下一站，会不会又是一朵云？',
  en:'The root took Didi in. Tiny water-carrying tubes led upward into a leaf. “Thank you!” rustled the willow. Later, Didi became invisible vapor again and left through a tiny leaf pore. “Trees are connected to the sky, too!” Didi wondered whether another cloud might be next.',
  why:'树为什么也能把水送进空气？',whyEn:'How do trees send water into the air?',
  factZh:'根吸收的水能沿植物的输水组织移动。叶片中的水蒸发，并通过气孔进入空气，叫蒸腾。植物利用水维持生命，水不只是“被喝掉就结束了”。图中的气孔和输水通道被放大，真实叶片不会冒出白烟。',
  factEn:'Roots absorb water, which can move through water-carrying tissue. Water evaporates inside leaves and escapes through pores called stomata. This is transpiration. Plants use water to live. The enlarged pore is a teaching view; real leaves do not puff white vapor.',
  qZh:'叶子送进空气里的水蒸气，看得见吗？',qEn:'Can we see the water vapor leaving a leaf?',choicesZh:['看不见','看得见，是白烟'],choicesEn:['No, it is invisible','Yes, it is white smoke'],answer:0,feedbackZh:'你已经记住了：水蒸气看不见，植物也参与水循环。',feedbackEn:'You remembered! Vapor is invisible, and plants join the water cycle.'},
 {title:'我把故事带回来了',titleEn:'I Brought Home a Story',act:4,img:'assets/12-home.webp',
  zh:'又经过一段长长的旅行，滴滴跟着另一场雨落进小溪，终于回到池塘。“你真的找到云了？”阿跳瞪大眼睛。滴滴点点头：“我去过云里面，还走过泥土和树叶！”它停了停：“不过，雨不是我叫来的。是阳光、空气和水，一起完成的旅行。”',
  en:'After another long journey, a later rain brought Didi into the stream and back to the pond. “Did you really find the clouds?” asked Frog. “I went inside one—and through soil and a leaf!” said Didi. “But I did not order the rain. Sunlight, air, and water made the journey happen.”',
  why:'水一定会回到原来的池塘吗？',whyEn:'Must water return to its first pond?',
  factZh:'不一定。滴滴回到同一个池塘，是我们为故事安排的巧合。真实的水可能到大海、远方的湖泊，或在冰雪和地下停留很久。水循环没有固定起点，也不是每滴水按同一个顺序绕圈，更没有固定的回家时间。',
  factEn:'No. Returning to this very pond is a coincidence in our story. Real water may reach an ocean or distant lake, or remain in ice or underground. There is no fixed starting point, route, or homecoming time for every drop.',
  qZh:'下一次，滴滴还可能去哪里？',qEn:'Where could Didi go next time?',choicesZh:['大海、湖泊或别的地方','只能回这个池塘'],choicesEn:['An ocean, lake, or elsewhere','Only this same pond'],answer:0,feedbackZh:'是的！结束的是这一次故事，水的旅行还会继续。',feedbackEn:'Yes! This story ends, but water keeps traveling.'},
 {title:'把天空和大地连起来',titleEn:'Connect the Sky and the Land',act:5,img:'assets/13-map.webp',
  zh:'阿跳在荷叶上画了一张旅行地图。“太阳提供能量，水可以变成水蒸气；空气冷却，小水滴聚成云；水滴长大，雨又落下来。”滴滴补充：“别忘了泥土、树叶和河流！这张地图有好多条路，轮到你带我们走一遍啦。”',
  en:'Frog made a travel map. “The Sun gives energy. Water can become vapor. Cooling air helps droplets form a cloud. Growing drops can fall as rain.” Didi added, “Remember soil, leaves, and rivers! Our map has many routes. Now you can guide us.”',
  why:'两位推动旅行的帮手',whyEn:'Two helpers that keep water moving',
  factZh:'太阳的能量帮助水蒸发；重力让雨往下落、河水往低处流。风搬运空气中的水，植物也参与其中。下面的顺序游戏只练习一条常见路线，并不代表所有水滴都走这条路。',
  factEn:'Solar energy helps evaporation. Gravity makes rain fall and water flow downhill. Wind transports water in air, and plants take part. The sequence game below follows just one possible route, not the route of every drop.',
  qZh:'把这条常见路线接起来',qEn:'Build this common route',sequence:true},
 {title:'冷杯子真的漏水了吗？',titleEn:'Is the Cold Cup Leaking?',act:5,img:'assets/14-cup.webp',
  zh:'故事讲完了，阿跳还想亲眼看一次。“不用飞到云里，”滴滴说，“在桌上也能找到线索！”和大人一起，把冰水装进一个不易碎的杯子，再摆一杯常温水。先擦干杯外，等一会儿。哪只杯子外面更容易出现小水珠？',
  en:'Frog wanted to see a clue for himself. “You need not fly into a cloud,” said Didi. With a grown-up, put ice water in an unbreakable cup and place a room-temperature cup beside it. Dry both outsides. Wait and look. Which cup is more likely to grow beads outside?',
  why:'杯外的水从哪里来？',whyEn:'Where does the water outside come from?',
  factZh:'空气中的水蒸气遇到足够冷的杯壁，会凝结成水珠，并不是穿过杯壁漏出来的。干燥天气里，水珠可能不明显；可以多等一会儿，但“没看到”也要如实记录。只观察，不喝实验用水；冰块由大人放入。',
  factEn:'Vapor in the surrounding air can condense on a cold enough cup. It has not leaked through the wall. In dry air, beads may be hard to see. Record what actually happens, even if nothing appears. A grown-up handles the ice; do not drink the experiment water.',
  qZh:'如果冷杯外面出现水珠，它主要来自哪里？',qEn:'If beads appear outside the cold cup, where do they come from?',choicesZh:['周围空气中的水蒸气','水穿过了完整的杯壁'],choicesEn:['Water vapor in the air','Water leaking through the wall'],answer:0,feedbackZh:'对！你在桌上观察到了“凝结”。记下你的观察，不必让结果和猜想一样。',feedbackEn:'Yes! You observed condensation. Record the result honestly, even if it differs from your guess.'},
 {title:'小小云朵讲解员',titleEn:'You Are a Cloud Explorer',act:5,img:'assets/13-map.webp',
  zh:'现在，轮到你给阿跳讲故事啦：滴滴为什么忽然看不见？它怎样加入一朵云？云里的小水珠怎样长成雨？你可以指着地图慢慢说，也可以挑一个最喜欢的词，讲给家人听。阿跳已经坐好，等你开讲了！',
  en:'Now tell Frog the story! Why did Didi become invisible? How did it join a cloud? How did small droplets grow into rain? Point to the map, take your time, and choose a favorite word to explain. Frog is ready to listen!',
  why:'给一起读书的大人',whyEn:'For grown-ups reading along',
  factZh:'可以分两次读：第一次陪滴滴旅行，第二次打开“为什么”和观察问题。先听孩子自己的解释，再一起修正。能说出因果，比背出术语更重要。再次打开绘本会记住阅读位置，目录可以随时跳回最喜欢的一页。',
  factEn:'Try two readings: follow the adventure first, then explore the questions. Listen to your child’s explanation before refining it together. Explaining a cause matters more than memorizing a term. The book saves your place, and the contents menu lets you revisit any page.',
  glossary:[{en:'Cloud',zh:'云'},{en:'Water vapor',zh:'水蒸气'},{en:'Evaporation',zh:'蒸发'},{en:'Condensation',zh:'凝结'},{en:'Rain',zh:'雨'},{en:'Root',zh:'根'},{en:'Transpiration',zh:'蒸腾'},{en:'Water cycle',zh:'水循环'}]}
];
