(() => {
 'use strict';
 const U=BookUI,{$,t,el,btn}=U;let phase='water',foam=0,angle=0;
 const svgNS='http://www.w3.org/2000/svg';
 function shape(tag,attrs){const n=document.createElementNS(svgNS,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));return n;}
 function labels(){return [t('清水和油','Water and oil'),t('右边加清洁剂','Detergent on the right'),t('两边同样搅动','Stir both equally'),t('两边同样冲洗','Rinse both equally')];}
 function vessel(side){const state=SoapModel.state(phase,foam),right=side==='right',svg=$(side+'-vessel');svg.replaceChildren();svg.append(shape('path',{d:'M50 25V205Q50 220 65 220H255Q270 220 270 205V25',fill:'#fff',stroke:'#23667b','stroke-width':4}));svg.append(shape('path',{d:'M53 82H267V205Q267 217 255 217H65Q53 217 53 205Z',class:'water'}));
  // Oil remains visible after rinsing, in the collection tray: transported, never destroyed.
  const dispersed=right&&state.dispersed,rinse=state.rinse;
  if(dispersed){for(let i=0;i<9;i++){const cx=rinse?70+(i%5)*40:91+(i%3)*62,cy=rinse?264+Math.floor(i/5)*18:110+Math.floor(i/3)*37;svg.append(shape('circle',{cx,cy,r:7,class:'oil'}));if(!rinse)svg.append(shape('circle',{cx,cy,r:10,fill:'none',stroke:'#257d9b','stroke-width':2}));}}
  else{svg.append(shape('ellipse',{cx:160,cy:rinse?90:84,rx:rinse?49:63,ry:7,class:'oil'}));if(rinse)for(const cx of [90,120])svg.append(shape('circle',{cx,cy:267,r:7,class:'oil'}));}
  if(right&&state.hasDetergent&&!state.dispersed){for(let i=0;i<5;i++)svg.append(shape('circle',{cx:100+i*30,cy:110,r:5,fill:'#257d9b'}));}
  if(phase==='rub')svg.append(shape('path',{d:'M122 145Q160 123 198 145M190 135L198 145L186 147',fill:'none',stroke:'#286477','stroke-width':3}));
  if(rinse){svg.append(shape('path',{d:'M285 84V241H230',fill:'none',stroke:'#66a9bb','stroke-width':5}));svg.append(shape('path',{d:'M35 245V290H285V245',fill:'none',stroke:'#23667b','stroke-width':3}));svg.insertBefore(shape('rect',{x:37,y:255,width:246,height:33,fill:'#d8eef2'}),svg.firstChild);}
  if(right&&state.hasDetergent){for(let i=0;i<foam;i++)svg.append(shape('circle',{cx:85+(i%6)*28,cy:57-Math.floor(i/6)*15,r:6+(i%3),class:'foam'}));}
  svg.setAttribute('aria-label',(right?t('加清洁剂的一边：','With detergent: '):t('只有清水的一边：','Water only: '))+(dispersed?(rinse?t('小油滴随洗涤水进入下方收集盘','Oil droplets travel with wash water into the tray below'):t('小油滴分散在水中','Small oil droplets disperse in the water')):t('油仍较集中','Oil remains more clustered')));
 }
 function draw(){if(!$('left-vessel'))return;vessel('left');vessel('right');const stage=SoapModel.phases.indexOf(phase);$('phase-status').textContent=(stage+1)+' / 4 · '+labels()[stage];$('next-phase').textContent=stage===3?t('已完成，可重新比较','Complete — reset to compare again'):labels()[stage+1];$('next-phase').disabled=stage===3;document.querySelectorAll('[data-phase]').forEach(b=>b.setAttribute('aria-current',b.dataset.phase===phase?'step':'false'));$('result').textContent=[t('两边是同量的油和水。先看看油在水里怎样待着。','Both sides have equal oil and water. Look at how the oil sits in the water.'),t('只有右边加入清洁剂。现在还没有搅动。','Only the right side receives detergent. Neither side has been stirred yet.'),t('两边同样搅动。有清洁剂的一边，小油滴更容易分散在水里。','Both sides are stirred equally. With detergent, small oil droplets disperse more easily in water.'),t('两边同样冲洗。看下方收集盘：油没有消失，是跟着洗涤水离开了。','Both sides are rinsed equally. Look at the trays below: the oil did not vanish; it left with the wash water.')][stage];$('foam-slider').disabled=stage===0;$('foam-state').textContent=stage===0?t('先加入清洁剂，再改变泡泡的显示数量。','Add detergent before changing the displayed bubbles.'):t('泡泡只改变外观，不改变去油步骤。','Bubbles change the appearance, not the cleaning steps.');}
 function workbench(parent){const box=el('div','paper');box.append(el('h3','',t('同一张桌子，两份小比较','One table. Two little comparisons.')),el('p','hint',t('同量油、同量水、同样搅动和冲洗；只有右边加入清洁剂。','Equal oil, equal water, equal stirring and rinsing. Only the right side gets detergent.')));const flow=el('div','flow');SoapModel.phases.forEach((p,i)=>{const badge=el('span','',String(i+1));badge.dataset.phase=p;flow.append(badge);});box.append(flow);const grid=el('div','lab-grid');[['left',t('清水','Water only')],['right',t('清水 + 清洁剂','Water + detergent')]].forEach(([side,title])=>{const column=el('div');column.append(el('p','pair-label',title));const svg=shape('svg',{viewBox:'0 0 320 310',class:'viz',id:side+'-vessel',role:'img'});column.append(svg);grid.append(column);});box.append(grid);const status=el('p','metric');status.id='phase-status';status.setAttribute('role','status');const result=el('p','experiment-status');result.id='result';const controls=el('div','controls'),next=btn('',()=>{U.stop();phase=SoapModel.next(phase);draw();});next.id='next-phase';controls.append(next,btn(t('重新比较','Start again'),()=>{U.stop();phase='water';foam=0;$('foam-slider').value=foam;draw();}));box.append(status,result,controls);const lab=el('label','',t('泡泡看起来多一些，还是少一些？','Show more bubbles or fewer?'));lab.htmlFor='foam-slider';const range=el('input');range.id='foam-slider';range.type='range';range.min=0;range.max=18;range.step=3;range.value=foam;range.oninput=()=>{foam=Number(range.value);draw();};const hint=el('p','hint');hint.id='foam-state';box.append(lab,range,hint);parent.append(box);draw();}
 function molecule(parent){const box=el('div','paper');box.append(el('h3','',t('油和水之间，发生了什么？','What happens between oil and water?')));const grid=el('div','lab-grid'),svg=shape('svg',{viewBox:'0 0 320 260',class:'viz',role:'img','aria-label':t('蓝色亲水头朝外面的水，棕色亲油尾朝里面的油滴','Blue water-friendly heads face water outside; brown oil-friendly tails face the oil inside')});svg.id='molecule-svg';const info=el('div');info.append(el('p','',t('蓝色的一端朝水，棕色的一端靠近油。许多分子在交界处排列，帮助小油滴分散。','The blue ends face water; the brown ends reach toward oil. Many molecules arrange at the boundary and help droplets disperse.')),el('p','hint',t('蓝色圆头：亲水部分\n棕色线尾：亲油部分\n金色圆：小油滴','Blue heads: water-friendly parts\nBrown tails: oil-friendly parts\nGold circle: oil droplet')));grid.append(svg,info);box.append(grid,btn(t('转一点，检查方向','Rotate a little. Check the direction.'),()=>{U.stop();angle+=Math.PI/12;drawMolecule();}));parent.append(box);drawMolecule();}
 function drawMolecule(){const svg=$('molecule-svg');svg.replaceChildren();svg.append(shape('rect',{x:0,y:0,width:320,height:260,rx:28,class:'water'}),shape('circle',{cx:160,cy:130,r:52,class:'oil'}));for(let i=0;i<12;i++){const m=SoapModel.molecule(angle+i*Math.PI/6,52);svg.append(shape('line',{x1:160+m.head.x,y1:130+m.head.y,x2:160+m.tail.x,y2:130+m.tail.y,class:'molecule-tail','data-molecule':i}));svg.append(shape('circle',{cx:160+m.head.x,cy:130+m.head.y,r:6,class:'molecule-head'}));}}
 function bubbleQuestion(parent){const box=el('div','paper');box.append(el('h3','',t('泡泡多，就一定洗得更干净吗？','Do more bubbles always mean cleaner?')));const out=el('p','feedback');out.setAttribute('role','status');const controls=el('div','controls');controls.append(btn(t('一定是','Always'),()=>out.textContent=t('回到工作台，改变泡泡数量看看：去油步骤变了吗？再试一次。','Change the bubble display at the workbench. Do the cleaning steps change? Try again.')),btn(t('不一定','Not necessarily'),()=>out.textContent=t('对！要看合适的清洁剂、接触和揉搓，以及最后的冲洗。','Right! Look at the suitable detergent, contact and rubbing, and the final rinse.')));box.append(controls,out);parent.append(box);}
 function render(story){U.begin(story,t('沫沫的厨房发现','Momo’s kitchen discovery'),t('几颗油点，一张工作台，一次认真比较。','A few oily spots. One workbench. A careful comparison.'),[['kitchen',t('围裙脏了','Oily apron')],['compare',t('一起比较','Compare')],['small',t('看看小油滴','Look closer')],['finish',t('泡泡的秘密','About bubbles')]]);const start=U.section(t('01 · 围裙上的油点','01 · Oily spots on an apron'),'kitchen');U.scenes(start,['helper','water']);const compare=U.section(t('02 · 只改变一件事','02 · Change just one thing'),'compare');U.scenes(compare,['soap']);workbench(compare);const small=U.section(t('03 · 让油分散，再随水离开','03 · Disperse the oil. Rinse it away.'),'small');U.scenes(small,['two-ends','rub']);molecule(small);U.scenes(small,['rinse']);const finish=U.section(t('04 · 不只看泡泡','04 · Look beyond the bubbles'),'finish');U.scenes(finish,['bubbles','clean','finish']);bubbleQuestion(finish);U.scenes(finish,['try']);U.words(finish);U.notes(finish,[t('工作台为定性的分阶段模型，不是清洁率实测。两边初始油水相同、搅动与冲洗相同，右侧多一个清洁剂条件。画面压缩了时间，不比较不同清洁产品，也不承诺完全去油；真实结果受配方、剂量、水质、温度、污物和操作影响。','The workbench is a qualitative staged model, not a measured cleaning-efficiency test. Initial oil and water, stirring and rinsing are equal; only detergent differs. Time is compressed. It neither compares products nor promises complete oil removal. Real results depend on formulation, dose, water, temperature, soil and handling.'),t('分子与油滴未按比例。亲水头朝水、亲油尾靠油，展示界面排列，不代表所有清洁剂分子的真实形状。泡沫显示与去油状态独立，泡沫数量不能单独作为清洁能力的指标。清洗去除污染物和部分微生物，不等于灭菌。','Molecules and droplets are not to scale. The head-and-tail drawing shows orientation at an oil–water boundary, not every detergent’s exact shape. The foam display is independent of cleaning state; foam alone is not a cleaning-performance measure. Cleaning removes soil and some microbes; it is not sterilization.'),t('家庭比较需成人全程陪同，用少量食用油、水和成人选定的合适清洁剂。避免眼口，不混用清洁产品，不使用热水或玻璃容器；按产品说明使用并收拾清洁。','A grown-up must supervise any home comparison, using small amounts of cooking oil, water and a suitable detergent chosen by the adult. Keep away from eyes and mouth; never mix cleaning products. Avoid hot water and glass containers. Follow the product instructions and clean up.')],[['ACS · The Wonders of Water (2014), p.9','https://www.acs.org/content/dam/acsorg/education/outreach/celebrating-chemistry/2014-cced-celebrating-chemistry-english.pdf'],['CDC · About Handwashing','https://www.cdc.gov/clean-hands/about/index.html']]);}
 U.mount(render);window.SoapBook={stop:U.stop,getState:()=>({lang:U.lang,...SoapModel.state(phase,foam),angle})};
})();
