const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),T=require('./labs/shared/vendor/three.min.js');
const c={window:{}};vm.createContext(c);for(const f of ['interiors','gear','exterior']){vm.runInContext(fs.readFileSync(`labs/hsr/book-model/${f}.js`,'utf8'),c);Object.assign(c,c.window);}
const train=c.BookTrainExterior.create(T),gear=c.BookTrainGear;
for(const [id,x] of [['front',-5.6],['rear',5.5]])for(const kind of ['Bogie','Motor']){const a=gear['create'+kind](T,{id:kind.toLowerCase()+'-'+id,x});train.root.add(a.group);train.assemblies.push(a);}
for(const a of [gear.createPantograph(T),gear.createCoupler(T)]){train.root.add(a.group);train.assemblies.push(a);}
assert.equal(train.assemblies.length,14);const detailIds=new Set(),identities=new Set();let meshes=0,triangles=0;for(const a of train.assemblies){assert.ok(!identities.has(a.id));identities.add(a.id);assert.equal(a.group.parent,train.root);for(const layer of ['exterior','interior','ghost'])assert.equal(a[layer].parent,a.group);assert.equal(a.interior.visible,false);assert.equal(a.ghost.visible,false);Object.keys(a.details).forEach(id=>detailIds.add(id));a.group.traverse(o=>{if(!o.isMesh)return;meshes++;assert.equal(o.userData.region,a.region);for(const n of o.geometry.attributes.position.array)assert.ok(Number.isFinite(n));triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3;});}
vm.runInContext(fs.readFileSync('labs/hsr/detail-parts.js','utf8'),c);assert.deepEqual([...detailIds].sort(),Array.from(c.window.HSR_DETAILS,d=>d.id).sort());assert.ok(meshes<900&&triangles<500000);
train.root.updateMatrixWorld(true);for(const id of ['front','rear']){const a=train.assemblies.find(a=>a.id==='bogie-'+id);assert.equal(a.group.localToWorld(a.center.clone()).x,id==='front'?-5.6:5.5);}
// Curved trim must live on the actual exterior, not float off the carriage.
const nose=train.assemblies.find(a=>a.region==='cab');for(const name of ['Wraparound windshield','Tapered side cab window','Teardrop headlight housing','Central forward glazing'])assert.ok(nose.exterior.getObjectByName(name),name);
const body=train.assemblies.find(a=>a.id==='cabin-body');assert.ok(body.exterior.getObjectByName('Blue belt tapering before nose'));assert.ok(body.exterior.getObjectByName('Lower equipment skirt'));
const drive=(region,time,level)=>{const state={time,level,region,mechanism:level>0,spin:1.55};train.update(state);for(const a of train.assemblies)a.update?.(state);train.root.updateMatrixWorld(true);};
drive(undefined,0,0);const initial=[];train.root.traverse(o=>initial.push([o,o.position.clone(),o.quaternion.clone(),o.scale.clone()]));
for(const region of ['doors','windows','bogies','pantograph','motors','coupler']){drive(region,1,1);assert.ok(initial.some(([o,p,q,s])=>o.position.distanceTo(p)>.01||o.quaternion.angleTo(q)>.01||o.scale.distanceTo(s)>.01),region+' must move');drive(undefined,0,0);for(const[o,p,q,s]of initial){assert.ok(o.position.distanceTo(p)<1e-7&&o.quaternion.angleTo(q)<1e-7&&o.scale.distanceTo(s)<1e-7,region+' must restore its pose');}}
for(const region of ['bogies','motors']){drive(region,1,1);const angles=[];train.root.traverse(o=>angles.push([o,o.quaternion.clone()]));drive(region,2,1);assert.ok(angles.some(([o,q])=>o.quaternion.angleTo(q)>.1),'Time must keep '+region+' rotating with an explicit spin speed');}drive(undefined,0,0);
const bogie=train.assemblies.find(a=>a.id==='bogie-front');const bounds=new T.Box3().setFromObject(bogie.exterior);assert.ok(Math.abs(bounds.min.y+1.495)<.01,'Wheel treads/flanges align with rail top');const track=gear.createTrack(T,{from:-12,to:43});assert.equal(track.name,'train-display-track');const rail=new T.Box3().setFromObject(track);assert.equal(rail.min.x,-12);assert.equal(rail.max.x,43);
console.log(`PASS book train: 14 attached assemblies; ${detailIds.size} details; ${meshes} meshes / ${Math.round(triangles)} triangles; surface-mounted reference features, local centers, finite geometry and mechanisms, rail alignment.`);
