const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=__dirname,out=path.join(root,'.qa-labs');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);let file=path.resolve(root,'.'+pathname.replace(/^\/kids-books/,''));if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');if(!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.png':'image/png'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 try{
  const base=process.env.LAB_LIVE_BASE||`http://127.0.0.1:${server.address().port}/kids-books/`,page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));let documents=0;page.on('request',r=>{if(r.isNavigationRequest()&&r.frame()===page.mainFrame())documents++;});
  await page.goto(base+'labs/airplane/');await page.waitForFunction(()=>window.airplaneLab?.snapshot().renderer.calls>0);
  assert.ok(await page.locator('button[data-enter-engine]').count()>0,'Engine entry must be a same-page button');
  await page.locator('#explode').fill('40');await page.waitForFunction(()=>Math.abs(airplaneLab.snapshot().explosion-.4)<.005);await page.locator('[data-part="engines"]').click();
  const before=await page.evaluate(()=>airplaneLab.snapshot()),p=await page.evaluate(()=>airplaneLab.projectPart('engines'));
  await page.mouse.dblclick(p.x,p.y,{delay:90});await page.waitForFunction(()=>window.airplaneDiscovery?.mode==='engine');
  assert.equal(documents,1,'No main-document navigation entering detail');assert.equal(await page.locator('iframe').count(),0);
  await page.waitForFunction(()=>window.engineDiscovery?.snapshot().rendered);
  assert.ok(await page.locator('#engine-depth #engine-viewport canvas').isVisible());assert.ok(await page.locator('#aircraft-overview').isHidden());
  await page.locator('#engine-depth #shell-open').fill('100');await page.locator('#engine-depth [data-engine-part="fan"]').click();await page.locator('#engine-depth #step').click();await page.locator('#engine-depth [data-task="find"]').click();await page.locator('#engine-depth [data-answer="fan"]').click();assert.equal(await page.evaluate(()=>engineDiscovery.snapshot().journal.explained.includes('find')),true);
  await page.screenshot({path:path.join(out,'inline-engine-desktop.png'),fullPage:true});
  await page.locator('#engine-depth [data-return-airplane="engines"]').first().click();await page.waitForFunction(()=>airplaneDiscovery.mode==='airplane');
  assert.equal(documents,1);const after=await page.evaluate(()=>airplaneLab.snapshot());assert.equal(after.targetExplosion,before.targetExplosion);assert.ok(Math.abs(after.camera.distance-before.camera.distance)<.1);assert.equal(after.selected,'engines');
  await page.locator('button[data-enter-engine]').first().click();await page.waitForFunction(()=>airplaneDiscovery.mode==='engine');assert.equal(await page.locator('#engine-depth #shell-open').inputValue(),'100');assert.equal(await page.locator('#engine-depth #engine-name').textContent(),'Fan');
  await page.locator('#engine-depth #play').click();await page.waitForTimeout(150);await page.goBack();await page.waitForFunction(()=>airplaneDiscovery.mode==='airplane');const t=await page.evaluate(()=>engineDiscovery.snapshot().time);await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>engineDiscovery.snapshot().time),t,'Hidden engine stops animation');await page.goForward();await page.waitForFunction(()=>airplaneDiscovery.mode==='engine');
  await page.locator('body > header #language').click();assert.ok(await page.locator('#engine-depth #engine-zh').isHidden());await page.locator('body > header #language').click();
  await page.locator('#engine-depth .next-discovery a').click();await page.waitForFunction(()=>airplaneDiscovery.mode==='airplane'&&airplaneLab.snapshot().selected==='wings');assert.equal(documents,1);
  await page.setViewportSize({width:390,height:844});await page.locator('button[data-enter-engine]').first().click();await page.waitForFunction(()=>airplaneDiscovery.mode==='engine');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,'inline-engine-mobile.png'),fullPage:true});
  await page.reload();await page.waitForFunction(()=>window.airplaneDiscovery?.mode==='engine');assert.equal(await page.locator('#engine-depth [data-engine-part]').count(),8);assert.equal(await page.locator('#engine-depth canvas').count(),1);assert.equal(errors.length,0,errors.join('\n'));
  for(const route of ['bypass','core']){await page.locator(`#engine-depth [data-flow="${route}"]`).click();await page.locator('#engine-depth #step').click();}await page.locator('#engine-depth [data-task="routes"]').click();await page.locator('#engine-depth [data-answer="bypass"]').click();
  await page.locator('#engine-depth #shaft-toggle').click();await page.locator('#engine-depth #step').click();await page.locator('#engine-depth [data-task="connect"]').click();await page.locator('#engine-depth [data-answer="shaft"]').click();await page.locator('#engine-depth [data-engine-part="combustor"]').click();await page.locator('#engine-depth [data-task="fuel"]').click();await page.locator('#engine-depth [data-answer="combustor"]').click();assert.equal(await page.evaluate(()=>engineDiscovery.snapshot().journal.explained.length),4);
  await page.locator('#engine-depth #clear-progress').click();await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>airplaneDiscovery.mode),'engine','Escape closes modal before leaving depth');await page.keyboard.press('Escape');await page.waitForFunction(()=>airplaneDiscovery.mode==='airplane');
  const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const touch=await mobile.newPage();await touch.goto(base+'labs/airplane/');await touch.waitForFunction(()=>window.airplaneLab?.snapshot().renderer.calls>0);await touch.locator('button[data-enter-engine]').first().tap();await touch.waitForFunction(()=>airplaneDiscovery.mode==='engine');await touch.locator('#engine-depth .aircraft-context').tap();await touch.waitForFunction(()=>airplaneDiscovery.mode==='airplane');await mobile.close();
  const recovery=await browser.newContext(),retry=await recovery.newPage();await retry.route('**/engine/index.html',r=>r.fulfill({status:503,body:'unavailable'}));await retry.goto(base+'labs/airplane/');await retry.waitForFunction(()=>window.airplaneLab?.snapshot().renderer.calls>0);await retry.locator('button[data-enter-engine]').first().click();await retry.locator('#discovery-error').waitFor({state:'visible'});assert.equal(await retry.evaluate(()=>airplaneDiscovery.mode),'airplane');await retry.unroute('**/engine/index.html');await retry.locator('#discovery-error button').click();await retry.waitForFunction(()=>airplaneDiscovery.mode==='engine');await retry.locator('#engine-depth .aircraft-context').click();await retry.waitForFunction(()=>airplaneDiscovery.mode==='airplane');assert.ok(await retry.evaluate(()=>document.activeElement.matches('#aircraft-overview [data-enter-engine]')),'Return after retry restores visible keyboard focus');await recovery.close();
  const cancellation=await browser.newContext(),cancel=await cancellation.newPage();await cancel.route('**/engine/index.html',async r=>{await new Promise(done=>setTimeout(done,900));await r.continue();});await cancel.goto(base+'labs/airplane/');await cancel.waitForFunction(()=>window.airplaneLab?.snapshot().renderer.calls>0);await cancel.locator('button[data-enter-engine]').first().click();await cancel.locator('#cancel-discovery').click();await cancel.evaluate(()=>{window.cancellations=0;speechSynthesis.cancel=()=>window.cancellations++;});await cancel.waitForTimeout(1300);assert.equal(await cancel.evaluate(()=>window.cancellations),0,'Canceled background mount cannot stop another narration');assert.equal(await cancel.evaluate(()=>airplaneDiscovery.mode),'airplane');await cancel.locator('button[data-enter-engine]').first().click();await cancel.waitForFunction(()=>airplaneDiscovery.mode==='engine');assert.equal(await cancel.locator('#engine-depth canvas').count(),1);await cancellation.close();
  console.log('PASS inline: mesh double-click, no navigation/iframe, task, restore view/explosion, retained detail, back/forward, suspend, bilingual, wings, mobile, deep reload');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
