const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=__dirname,out=path.join(root,'.qa-labs');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const p=decodeURIComponent(new URL(req.url,'http://localhost').pathname);let f=path.resolve(root,'.'+p.replace(/^\/kids-books/,''));if(!f.startsWith(root+path.sep)){res.writeHead(403);return res.end();}if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.png':'image/png'})[path.extname(f)]||'application/octet-stream');fs.createReadStream(f).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const base=process.env.LAB_LIVE_BASE||`http://127.0.0.1:${server.address().port}/kids-books/`;await page.goto(base+'labs/airplane/');await page.waitForFunction(()=>window.airplaneLab?.snapshot().renderer.calls>0);
 assert.equal(await page.locator('#detail-list').count(),1,'Original airplane must expose attached internal details');
 const canvas=await page.locator('#viewport canvas').elementHandle();await page.evaluate(()=>window.originalRenderer=airplaneLab.snapshot().modelId);
 assert.equal(await page.locator('canvas').count(),1);assert.equal(await page.locator('iframe').count(),0);
 await page.locator('[data-part="engines"]').click();await page.locator('[data-detail="engine.fan"]').click();await page.waitForFunction(()=>airplaneLab.snapshot().camera.distance<2.5);assert.equal(await page.locator('#part-name').textContent(),'Fan');assert.ok(await page.evaluate(()=>airplaneLab.snapshot().cutaway>.6));
 assert.ok(await canvas.evaluate(c=>c.isConnected));assert.equal(await page.evaluate(()=>airplaneLab.snapshot().modelId),await page.evaluate(()=>window.originalRenderer));
 await page.locator('#mechanism').fill('80');await page.locator('#mechanism-play').click();await page.waitForTimeout(200);await page.locator('#mechanism-play').click();assert.ok(await page.evaluate(()=>airplaneLab.snapshot().simulationTime>0));
 await page.screenshot({path:path.join(out,'rich-engine.png'),fullPage:true,animations:'disabled'});
 // Hit the exposed geometry itself, without using a label or detail chip.
 await page.waitForTimeout(1200);await page.locator('#labels').evaluate(e=>e.style.visibility='hidden');
 const hitBox=await page.locator('canvas').boundingBox();let meshDetail=false;
 for(const [x,y]of[[.48,.52],[.56,.55],[.62,.5],[.42,.5],[.5,.6]]){await page.locator('[data-part="engines"]').click();await page.mouse.click(hitBox.x+hitBox.width*x,hitBox.y+hitBox.height*y);const picked=await page.evaluate(()=>airplaneLab.snapshot().detail);if(picked?.startsWith('engine.')){meshDetail=true;break;}}
 assert.ok(meshDetail,'A click on visible engine geometry must select an internal detail');
 await page.locator('#labels').evaluate(e=>e.style.visibility='');
 for(const [region,id,name]of[['fuselage','cabin.seats','Passenger seats'],['cockpit','cockpit.panel','Instrument panel'],['wings','wing.ribs','Wing ribs'],['gear','gear.brake','Wheel brake']]){await page.locator(`[data-part="${region}"]`).click();await page.locator(`[data-detail="${id}"]`).click();await page.waitForTimeout(2200);assert.equal(await page.locator('#part-name').textContent(),name);assert.equal(await page.evaluate(()=>airplaneLab.snapshot().detail),id);assert.equal(await page.locator('canvas').count(),1);await page.screenshot({path:path.join(out,'rich-'+region+'.png'),fullPage:true,animations:'disabled'});}
 // Every detail is visible in English and remains in the same root model.
 for(const d of await page.evaluate(()=>AIRPLANE_DETAILS)){await page.locator(`[data-part="${d.region}"]`).click();await page.locator(`[data-detail="${d.id}"]`).click();assert.equal(await page.locator('#part-en').textContent(),d.en);assert.equal(await page.evaluate(()=>airplaneLab.snapshot().modelId),await page.evaluate(()=>window.originalRenderer));}
 await page.evaluate(()=>{window.spoken=[];speechSynthesis.speak=u=>window.spoken.push(u.text);});await page.locator('#speak').click();assert.match((await page.evaluate(()=>window.spoken))[0],/Landing gear bay/);
 // Observation tasks still require exploring the parts, and persist on reload.
 await page.locator('[data-part="engines"]').click();
 for(const id of ['engine.fan','engine.bypass','engine.combustor','engine.shaft']){await page.locator(`[data-detail="${id}"]`).click();await page.waitForTimeout(600);await page.locator('#mechanism-step').click();}
 await page.locator('#engine-missions summary').click();
 for(const task of await page.evaluate(()=>ENGINE_CONTENT.tasks)){await page.locator('#engine-task').selectOption(task.id);const answer=task.answers.find(a=>a[0]===task.correct);await page.locator('#engine-task-answers button').filter({hasText:answer[1]+' · '+answer[2]}).click();assert.match(await page.locator('#engine-task-feedback').textContent(),/已保存/);}
 // Zoom alone reveals the original engine, with no manually opened shell.
 await page.locator('#home-view').click();await page.locator('#cutaway').fill('0');await page.locator('#auto-reveal').check();await page.locator('[data-part="engines"]').click();await page.locator('#focus-part').click();await page.waitForFunction(()=>airplaneLab.snapshot().camera.distance<3.1);await page.locator('#zoom-in').click();await page.locator('#zoom-in').click();await page.waitForFunction(()=>airplaneLab.snapshot().cutaway>.9);assert.equal(await page.locator('#cutaway').inputValue(),'0');
 const beforePan=await page.evaluate(()=>airplaneLab.snapshot().camera.target),box=await page.locator('canvas').boundingBox();await page.mouse.move(box.x+box.width*.4,box.y+box.height*.6);await page.mouse.down({button:'right'});await page.mouse.move(box.x+box.width*.5,box.y+box.height*.6,{steps:6});await page.mouse.up({button:'right'});await page.waitForTimeout(500);const afterPan=await page.evaluate(()=>airplaneLab.snapshot().camera.target);assert.ok(Math.hypot(afterPan.x-beforePan.x,afterPan.y-beforePan.y,afterPan.z-beforePan.z)>.02);
 await page.locator('#home-view').click();await page.waitForFunction(()=>airplaneLab.snapshot().camera.distance>12);await page.locator('[data-part="engines"]').click();const p=await page.evaluate(()=>airplaneLab.projectPart('engines'));await page.mouse.move(p.x,p.y);await page.mouse.wheel(0,-800);await page.waitForFunction(()=>airplaneLab.snapshot().camera.distance<9);assert.equal(await page.locator('canvas').count(),1);assert.equal(new URL(page.url()).pathname,new URL(base+'labs/airplane/').pathname);
 await page.locator('#home-view').click();await page.locator('#assembly-options').evaluate(e=>e.open=true);await page.locator('#explode-button').click();await page.waitForFunction(()=>airplaneLab.snapshot().explosion>.99);await page.locator('#assemble').click();await page.waitForFunction(()=>airplaneLab.snapshot().explosion<.01);
 await page.setViewportSize({width:390,height:844});await page.locator('[data-part="wings"]').click();await page.locator('[data-detail="wing.spar"]').click();await page.waitForTimeout(1500);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#part-en').scrollIntoViewIfNeeded();const mobileCanvas=await page.locator('canvas').boundingBox();assert.ok(mobileCanvas.y>=0&&mobileCanvas.y+mobileCanvas.height<400,'Model stays visible while reading');await page.screenshot({path:path.join(out,'rich-mobile.png'),animations:'disabled'});await page.locator('#controls-toggle').click();assert.equal(await page.locator('#mechanism').isVisible(),true);await page.locator('#mechanism').fill('70');await page.locator('#controls-toggle').click();
 const touch=await page.context().newCDPSession(page),touchBox=await page.locator('canvas').boundingBox(),cx=touchBox.x+touchBox.width*.5,cy=touchBox.y+touchBox.height*.6;
 const beforePinch=await page.evaluate(()=>airplaneLab.snapshot().camera.distance);
 await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:cx-25,y:cy},{id:2,x:cx+25,y:cy}]});await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x:cx-55,y:cy},{id:2,x:cx+55,y:cy}]});await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForFunction(d=>airplaneLab.snapshot().camera.distance<d*.8,beforePinch);await touch.detach();
 await page.reload();await page.waitForFunction(()=>window.airplaneLab?.snapshot().renderer.calls>0);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('little-wings:whole-airplane:v1')).explained.length),4);
 await page.evaluate(()=>{localStorage.removeItem('little-wings:whole-airplane:v1');localStorage.setItem('little-wings:engine-discovery:v1',JSON.stringify({found:['fan'],operated:['spin'],explained:['find']}));});await page.goto(base+'labs/airplane/#engine');await page.waitForFunction(()=>airplaneLab.snapshot().selected==='engines');await page.reload();await page.waitForFunction(()=>window.airplaneLab?.snapshot().renderer.calls>0);assert.equal(await page.evaluate(()=>airplaneLab.snapshot().selected),'engines');assert.ok(await page.evaluate(()=>airplaneLab.snapshot().visited.includes('engine.fan')));assert.ok(await page.evaluate(()=>JSON.parse(localStorage.getItem('little-wings:whole-airplane:v1')).explained.includes('find')));assert.equal(await page.locator('canvas').count(),1);
 assert.equal(errors.length,0,errors.join('\n'));console.log('PASS rich airplane: same root/canvas, 24 details, close zoom, automatic reveal, mechanisms, all regions, wheel zoom, assembly and mobile');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});

