const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=__dirname,out=path.join(root,'.qa-labs');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/kids-books/,''));if(!f.startsWith(root+path.sep)){res.writeHead(403);return res.end();}if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.png':'image/png'})[path.extname(f)]||'application/octet-stream');fs.createReadStream(f).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
 const page=await browser.newPage({viewport:{width:1440,height:940},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));const base=process.env.LAB_LIVE_BASE||`http://127.0.0.1:${server.address().port}/kids-books/`;
 await page.goto(base+'labs/airplane/');await page.waitForFunction(()=>window.airplaneLab?.snapshot().generation===3&&airplaneLab.snapshot().renderer.calls>0);
 const canvas=await page.locator('canvas').elementHandle(),identity=await page.evaluate(()=>airplaneLab.snapshot().modelId);assert.equal(await page.locator('canvas').count(),1);
 await page.screenshot({path:path.join(out,'v3-whole.png')});if(process.env.UPDATE_LAB_PREVIEW)await page.locator('#viewport').screenshot({path:path.join(root,'labs/airplane/preview.png')});
 const beforeZoom=await page.evaluate(()=>airplaneLab.snapshot().camera.distance);const zoomPoint=await page.evaluate(()=>airplaneLab.projectPart('engine-right'));await page.mouse.move(zoomPoint.x,zoomPoint.y);await page.mouse.wheel(0,-750);await page.waitForFunction(d=>airplaneLab.snapshot().camera.distance<d*.65,beforeZoom);assert.equal(await page.evaluate(()=>airplaneLab.snapshot().modelId),identity);assert.equal(await page.evaluate(()=>airplaneLab.snapshot().mode),'auto');await page.locator('#home-view').click();await page.waitForFunction(()=>airplaneLab.snapshot().selected===null);
 const p=await page.evaluate(()=>airplaneLab.projectPart('engine-right'));await page.mouse.dblclick(p.x,p.y);await page.waitForFunction(()=>airplaneLab.snapshot().selected==='engines');
 await page.locator('[data-part="engines"]').click();await page.waitForFunction(()=>airplaneLab.snapshot().near>.95);await page.locator('[data-view="inside"]').click();await page.waitForFunction(()=>airplaneLab.snapshot().reveal>.95);
 const state=await page.evaluate(()=>airplaneLab.snapshot());assert.ok(state.assemblies.filter(a=>a.id!==state.assembly).every(a=>!a.interior&&a.ghost&&!a.exterior),'Unrelated interiors must be hidden, only simple silhouettes remain');
 await page.screenshot({path:path.join(out,'v3-engine.png')});
 for(const [region,id]of[['engines','engine.fan'],['engines','engine.combustor'],['fuselage','cabin.seats'],['cockpit','cockpit.panel'],['wings','wing.ribs'],['gear','gear.brake']]){await page.locator(`[data-part="${region}"]`).click();await page.locator(`[data-detail="${id}"]`).click();await page.waitForFunction(id=>airplaneLab.snapshot().detail===id&&airplaneLab.snapshot().reveal>.95,id);assert.equal(await page.evaluate(()=>airplaneLab.snapshot().modelId),identity);await page.screenshot({path:path.join(out,'v3-'+id.replace('.','-')+'.png')});}
 for(const d of await page.evaluate(()=>AIRPLANE_DETAILS)){await page.locator(`[data-part="${d.region}"]`).click();await page.locator(`[data-detail="${d.id}"]`).click();assert.equal(await page.locator('#part-en').textContent(),d.en);}
 await page.locator('[data-part="engines"]').click();for(const id of ['engine.fan','engine.shaft','engine.combustor']){await page.locator(`[data-detail="${id}"]`).click();await page.waitForFunction(()=>airplaneLab.snapshot().reveal>.95);await page.locator('#mechanism-step').click();}
 await page.locator('#mechanism-play').click();const tick=await page.evaluate(()=>airplaneLab.snapshot().simulationTime);await page.waitForFunction(t=>airplaneLab.snapshot().simulationTime>t+.1,tick);await page.locator('#mechanism-play').click();const paused=await page.evaluate(()=>airplaneLab.snapshot().simulationTime);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await page.evaluate(()=>airplaneLab.snapshot().simulationTime),paused);
 await page.locator('#engine-missions summary').click();for(const t of await page.evaluate(()=>ENGINE_CONTENT.tasks)){await page.locator('#engine-task').selectOption(t.id);const a=t.answers.find(a=>a[0]===t.correct);await page.locator('#task-answers button').filter({hasText:a[1]+' · '+a[2]}).click();assert.match(await page.locator('#task-feedback').textContent(),/已保存/);}
 await page.evaluate(()=>{window.spoken=[];speechSynthesis.speak=u=>window.spoken.push(u.text);});await page.locator('#speak').click();assert.ok((await page.evaluate(()=>window.spoken))[0].includes('Combustor'));
 await page.locator('#language').click();assert.equal(await page.locator('#part-zh').isVisible(),false);await page.locator('#language').click();
 await page.locator('#home-view').click();await page.waitForFunction(()=>airplaneLab.snapshot().near===0);assert.ok((await page.evaluate(()=>airplaneLab.snapshot().assemblies)).every(a=>a.exterior&&!a.interior&&!a.ghost));
 await page.locator('#explode-button').click();await page.waitForFunction(()=>airplaneLab.snapshot().explosion>.99);await page.screenshot({path:path.join(out,'v3-exploded.png')});await page.locator('#explode-button').click();await page.waitForFunction(()=>airplaneLab.snapshot().explosion<.01);
 for(const [width,height]of[[1024,768],[390,844]]){await page.setViewportSize({width,height});await page.locator('[data-part="engines"]').click();await page.locator('[data-detail="engine.fan"]').click();await page.waitForFunction(()=>airplaneLab.snapshot().reveal>.9);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const c=await page.locator('canvas').boundingBox(),tools=await page.locator('.stage-tools').boundingBox();assert.ok(c.y+c.height<=tools.y+1);if(width<800){const en=await page.locator('#part-en').boundingBox();assert.ok(en.y>=tools.y+tools.height&&en.y+en.height<=height,'English must be visible below sticky model');}await page.screenshot({path:path.join(out,'v3-'+width+'.png')});if(width<800){const touch=await page.context().newCDPSession(page),cx=c.x+c.width/2,cy=c.y+c.height/2,d=await page.evaluate(()=>airplaneLab.snapshot().camera.distance);await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx-25,y:cy,id:1},{x:cx+25,y:cy,id:2}]});await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cx-50,y:cy,id:1},{x:cx+50,y:cy,id:2}]});await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForFunction(d=>airplaneLab.snapshot().camera.distance<d*.7,d);await touch.detach();}}
 assert.ok(await canvas.evaluate(c=>c.isConnected));assert.equal(errors.length,0,errors.join('\n'));await page.reload();await page.waitForFunction(()=>window.airplaneLab?.snapshot().renderer.calls>0);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('little-wings:whole-airplane:v1')).explained.length),4);
 await page.setViewportSize({width:1440,height:940});
 for(const part of await page.evaluate(()=>PLANE_PARTS)){await page.locator(`[data-part="${part.id}"]`).click();assert.equal(await page.locator('#part-en').textContent(),part.en);}
 await page.locator('.lab-navigation a').first().click();await page.waitForFunction(()=>window.LABS_CATALOG&&document.querySelector('.lab-card'));
 assert.equal(await page.locator('.lab-card.ready').count(),await page.evaluate(()=>LABS_CATALOG.filter(l=>l.status==='ready').length));
 for(const img of await page.locator('.lab-cover img').all())assert.ok(await img.evaluate(i=>i.complete&&i.naturalWidth>0));
 await page.locator('[data-lab-id="airplane"] .enter-lab').click();await page.waitForFunction(()=>window.airplaneLab?.snapshot().generation===3);
 await page.locator('.lab-navigation a').last().click();assert.ok(page.url().endsWith('/books/airplane/index.html'));await page.locator('.book-lab-link').click();await page.waitForFunction(()=>window.airplaneLab?.snapshot().generation===3);
 await page.goto(base+'labs/airplane/#engine');await page.waitForFunction(()=>window.airplaneLab?.snapshot().selected==='engines');assert.equal(errors.length,0,errors.join('\n'));
 console.log('PASS v3 browser: new model identity, direct engine double click, silhouette-only surroundings, 24 English details, local cutaway, tasks, speech, reassembly, desktop/tablet/mobile.');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
