// Native reader audio and real SW. LIVE URL is opt-in; default is a local fixture server.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),crypto=require('node:crypto');
let pw;try{pw=require('playwright');}catch{pw=require(process.env.PLAYWRIGHT_MODULE||'../.qa-deps/node_modules/playwright');}
const root=path.resolve(__dirname,'..'),books=['sound','soap'],read=p=>fs.readFileSync(path.join(root,p)),parse=s=>JSON.parse(s.slice(s.indexOf('{'),s.lastIndexOf('}')+1));
const raw=read('pwa-assets.js').toString(),catalog=parse(raw),stories=Object.fromEntries(books.map(b=>[b,JSON.parse(read(`books/${b}/story.json`))]));
const manifests=Object.fromEntries(books.map(b=>[b,JSON.parse(read(`books/${b}/audio-manifest.json`))]));
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
async function message(page,type,bookId){return page.evaluate(({type,bookId})=>new Promise((resolve,reject)=>{const ch=new MessageChannel(),timer=setTimeout(()=>reject(Error(type+' timeout')),120000);ch.port1.onmessage=({data})=>{if(data.type==='KB_PROGRESS'&&data.state==='running')return;clearTimeout(timer);ch.port1.close();resolve(data);};navigator.serviceWorker.controller.postMessage({type,bookId},[ch.port2]);}),{type,bookId});}
async function instrument(context){await context.addInitScript(()=>{const Native=window.Audio;window.__records=[];window.__fallbacks=0;window.Audio=function(src){const a=new Native(src),r={src,ended:false,error:null,duration:null,maxTime:0};a.playbackRate=4;r.audio=a;__records.push(r);a.addEventListener('loadedmetadata',()=>r.duration=a.duration);a.addEventListener('timeupdate',()=>r.maxTime=Math.max(r.maxTime,a.currentTime));a.addEventListener('ended',()=>{r.ended=true;r.endedAt=a.currentTime;});a.addEventListener('error',()=>r.error=a.error?.code||'unknown');return a;};const speak=window.speechSynthesis?.speak.bind(window.speechSynthesis);if(speak)window.speechSynthesis.speak=u=>{__fallbacks++;return speak(u);};});}
async function allAudio(page,base,label){const results=[];for(const book of books){await page.goto(base+`/books/${book}/`);await page.locator('[data-scene-id]').first().waitFor();for(const lang of ['zh','en']){if(await page.evaluate(()=>BookUI.lang)!==lang)await page.locator('#language').click();const jobs=[...stories[book].scenes.map(x=>({id:`scene-${x.id}-${lang}`,button:page.locator(`[data-scene-id="${x.id}"] button`).first()})),...stories[book].vocab.map((x,i)=>({id:`vocab-${x.id}-${lang}`,button:page.locator('.vocab button').nth(i)}))];for(const job of jobs){const n=await page.evaluate(()=>__records.length);await job.button.click();await page.waitForFunction(n=>__records[n]?.ended||__records[n]?.error,n,{timeout:60000});const rec=await page.evaluate(n=>{const {audio,...r}=__records[n];return {...r,active:__records.filter(x=>!x.audio.paused).length,fallbacks:__fallbacks};},n);const url=catalog.books[book].files.find(f=>f.includes('/audio/'+job.id+'.mp3?'));assert.equal(rec.src,url.replace(`books/${book}/`,''));assert.equal(rec.error,null);assert(rec.ended&&rec.duration>0&&rec.endedAt>=rec.duration-.08&&rec.maxTime>0);assert.equal(rec.active,0);assert.equal(rec.fallbacks,0);results.push({book,id:job.id,...rec});console.log(label,book,job.id,'ended',rec.duration);}}assert.deepEqual(results.filter(x=>x.book===book).map(x=>x.id).sort(),manifests[book].entries.map(x=>x.id).sort());
// Confirm interruption of real MP3 objects, then sound-vs-narration mutual exclusion.
const first=page.locator('[data-scene-id] button').first();for(const action of ['stop','language']){await first.click();await page.waitForFunction(()=>__records.at(-1).audio.currentTime>.1);await page.locator('#'+action).click();assert(await page.evaluate(()=>__records.every(r=>r.audio.paused)));}
if(book==='sound'){if(await page.evaluate(()=>BookUI.lang)!=='zh')await page.locator('#language').click();await page.locator('#enable-sound').check();await page.getByRole('button',{name:'轻敲小鼓',exact:true}).click();await page.waitForFunction(()=>SoundBook.getState().activeVoice);await first.click();assert.equal(await page.evaluate(()=>SoundBook.getState().activeVoice),false);await page.waitForFunction(()=>__records.at(-1).audio.currentTime>.1);await page.getByRole('button',{name:'轻敲小鼓',exact:true}).click();assert(await page.evaluate(()=>__records.every(r=>r.audio.paused)));await page.locator('#stop').click();}
}return results;}
module.exports={instrument,allAudio,message};
if(require.main===module)(async()=>{
for(const book of books){assert.equal(catalog.books[book].complete,true,'READY + regenerated full catalog required');assert.equal(catalog.books[book].files.filter(f=>f.includes('/audio/')).length,manifests[book].entries.length);}
const live=process.env.EVERYDAY_LIVE_URL;if(live)assert(/^https:\/\//.test(live));let upgraded=false,server,base=live;
const prior=JSON.parse(JSON.stringify(catalog));prior.version='everyday-partial-fixture';for(const b of books){prior.books[b].missingAudio=prior.books[b].files.filter(f=>f.includes('/audio/'));prior.books[b].files=prior.books[b].files.filter(f=>!f.includes('/audio/'));prior.books[b].bytes=prior.books[b].files.reduce((sum,f)=>sum+read(f.split('?')[0]).length,0);prior.books[b].complete=false;}
if(!live){server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://local').pathname;let f=path.resolve(root,'.'+decodeURIComponent(pathname));if(!f.startsWith(root+path.sep))return res.writeHead(403).end();if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.webp':'image/webp','.mp3':'audio/mpeg'})[path.extname(f)]||'application/octet-stream');if(pathname==='/pwa-assets.js')return res.end(upgraded?raw:'self.KB_ASSETS='+JSON.stringify(prior)+';');if(pathname==='/sw.js')return res.end(read('sw.js')+'\n// fixture '+upgraded);fs.readFile(f,(e,b)=>e?res.writeHead(404).end():res.end(b));});await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;}
const out=path.join(root,live?'.deploy_verify/everyday-live':'.qa-labs/everyday-full');fs.mkdirSync(out,{recursive:true});const browser=await pw.chromium.launch({channel:'chrome',headless:true});const errors=[],hashes=[];let onlineContext,offlineContext;
try{
onlineContext=await browser.newContext({serviceWorkers:'block',viewport:{width:390,height:844}});await instrument(onlineContext);const onlinePage=await onlineContext.newPage();onlinePage.on('pageerror',e=>errors.push(e.message));
if(live){const c=await onlineContext.request.get(base+'/pwa-assets.js');assert.equal(c.status(),200);assert.equal(parse(await c.text()).version,catalog.version);const assets=[...new Set(['index.html','pwa-assets.js','sw.js','shared/pwa.js',...books.flatMap(b=>catalog.books[b].files),...catalog.shell.filter(f=>books.some(b=>f.startsWith(`books/${b}/`)))])];let next=0;const canonical=(b,f)=>/\.(js|json|html|css)$/.test(f.split('?')[0])?Buffer.from(b.toString().replace(/\r\n/g,'\n')):b;await Promise.all([0,1,2,3].map(async()=>{while(next<assets.length){const f=assets[next++],r=await onlineContext.request.get(base+'/'+f,{timeout:90000});assert.equal(r.status(),200,f);assert.equal(hash(canonical(await r.body(),f)),hash(canonical(read(f.split('?')[0]),f)),f);hashes.push(f);}}));console.log('LIVE_HASHES_PASS',hashes.length);}
const online=await allAudio(onlinePage,base,'ONLINE');await onlineContext.close();onlineContext=null;
offlineContext=await browser.newContext({viewport:{width:390,height:844}});await instrument(offlineContext);const page=await offlineContext.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/index.html');await page.waitForFunction(()=>!!navigator.serviceWorker.controller,null,{timeout:240000});
for(const b of ['moon','airplane'])assert.equal((await message(page,'KB_DOWNLOAD',b)).state,'done');
if(!live){for(const b of books){assert.equal((await message(page,'KB_DOWNLOAD',b)).state,'partial');}upgraded=true;await page.evaluate(async()=>{await (await navigator.serviceWorker.getRegistration()).update();});let s;const deadline=Date.now()+120000;do{s=await message(page,'KB_STATUS');if(s.version===catalog.version)break;await page.waitForTimeout(100);}while(Date.now()<deadline);assert.equal(s.version,catalog.version,'new worker must control the page');for(const b of books){assert.equal(s.books[b].cached,prior.books[b].files.length);assert.equal(s.books[b].total,catalog.books[b].files.length);assert(s.books[b].cached<s.books[b].total);}for(const b of ['moon','airplane'])assert.equal(s.books[b].cached,s.books[b].total);}
for(const b of books)assert.equal((await message(page,'KB_DOWNLOAD',b)).state,'done');const full=await message(page,'KB_STATUS');for(const b of books)assert.equal(full.books[b].cached,full.books[b].total);
// Cached bytes must equal the current URLs/files, not a stale similarly named audio.
for(const b of books){const files=catalog.books[b].files.filter(f=>f.includes('/audio/'));const actual=await page.evaluate(async files=>{const cache=await caches.open('kb-asset-v1'),rows={};for(const f of files){const r=await cache.match(new URL(f,location.href).href);if(!r)throw Error('Missing cached '+f);rows[f]=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await r.arrayBuffer()))).map(n=>n.toString(16).padStart(2,'0')).join('');}return rows;},files);for(const f of files)assert.equal(actual[f],hash(read(f.split('?')[0])),f);}
await offlineContext.setOffline(true);await page.reload();for(const b of books){const card=page.locator(`a.book-card[href="books/${b}/index.html"]`);await card.scrollIntoViewIfNeeded();assert(await card.locator('img').evaluate(x=>x.complete&&x.naturalWidth>0));}
const offline=await allAudio(page,base,'OFFLINE');for(const b of books){await page.goto(base+`/books/${b}/`);await page.locator('[data-scene-id]').first().waitFor();await page.locator('.art img').evaluateAll(xs=>xs.forEach(x=>x.loading='eager'));await page.waitForFunction(()=>Array.from(document.querySelectorAll('.art img')).every(x=>x.complete&&x.naturalWidth));await page.locator(b==='sound'?'#air .paper':'#compare .paper').screenshot({path:path.join(out,b+'-offline.png')});}
await offlineContext.setOffline(false);for(const b of books){const d=await message(page,'KB_DELETE',b);assert.equal(d.books[b].cached,0);const other=books.find(x=>x!==b);for(const keep of [other,'moon','airplane'])assert.equal(d.books[keep].cached,d.books[keep].total);assert.equal((await message(page,'KB_DOWNLOAD',b)).state,'done');}
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({base,version:catalog.version,online,offline,hashes,full:full.books,errors,partialUpgrade:!live,limits:'4x native playback without seek; mobile viewport not physical phone. No independent human hearing acceptance.'},null,2));console.log('EVERYDAY_FULL_PASS',online.length,offline.length,catalog.version);
}finally{await onlineContext?.close();await offlineContext?.close();await browser.close();if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}}
})().catch(e=>{console.error(e);process.exitCode=1;});
