const assert = require('node:assert/strict');
const { createHash } = require('node:crypto');
const { create } = require('../labs/earthquake/v3/audio.js');
const sha = value => createHash('sha256').update(value).digest('hex');
const content = { contentVersion: 'lab-v1', entries: [{ id: 'result-locked', kind: 'result', conceptId: 'elastic-strain', zh: '接缝卡住了。', en: 'The seam is locked.', narrationNeeded: true, contentVersion: 'lab-v1' }] };
const raw = JSON.stringify(content);
const source = content.entries[0];
const makeEntry = lang => {
  const text = source[lang];
  const id = `result-result-locked-${lang}`;
  const segments = [{ role: 'narrator', sourceText: text, spokenText: text }];
  const utterance = { kind: 'result', id: source.id, lang, text, segments };
  return { id, key: `lab:${id}`, owner: 'lab', itemId: source.id, kind: 'result', lang, text, segments, contentVersion: 'lab-v1', textSha256: sha(text), utteranceSha256: sha(JSON.stringify(utterance)), output: `audio/${id}.mp3`, status: 'ready', fileSha256: 'a'.repeat(64) };
};
const baseManifest = { schemaVersion: 2, topicId: 'earthquake', owner: 'lab', contentVersion: 'lab-v1', sourceSha256: sha(raw), entries: [makeEntry('zh'), makeEntry('en')] };
const responses = manifest => async url => {
  if (url === 'content.json') return { ok: true, text: async () => raw };
  if (url === 'audio-manifest.json' && manifest) return { ok: true, text: async () => JSON.stringify(manifest) };
  return { ok: false, status: 404 };
};
class FakeAudio {
  static instances = [];
  static deferred = false;
  constructor(src) { this.src = src; this.paused = true; this.pauseCount = 0; FakeAudio.instances.push(this); }
  play() {
    this.paused = false;
    if (!FakeAudio.deferred) return Promise.resolve();
    return new Promise(resolve => { this.resolvePlay = resolve; });
  }
  pause() { this.paused = true; this.pauseCount++; }
}
const options = manifest => ({ manifestUrl: 'audio-manifest.json', contentUrl: 'content.json', contentVersion: 'lab-v1', fetcher: responses(manifest), AudioClass: FakeAudio, baseUrl: 'https://example.test/labs/earthquake/' });

(async () => {
  const missing = create(options(null));
  await missing.ready;
  assert.equal(missing.available('result', 'result-locked', 'zh'), false, 'missing manifest cannot advertise narration');
  assert.equal((await missing.play('result', 'result-locked', 'zh')).ok, false);

  const stale = create(options({ ...baseManifest, sourceSha256: '0'.repeat(64) }));
  await stale.ready;
  assert.equal(stale.available('result', 'result-locked', 'zh'), false, 'stale source hash suppresses all clips');

  const partial = create(options({ ...baseManifest, entries: [makeEntry('zh')] }));
  await partial.ready;
  assert.equal(partial.available('result', 'result-locked', 'zh'), true);
  assert.equal(partial.available('result', 'result-locked', 'en'), false, 'missing English clip is never falsely enabled');

  const badUtterance = create(options({ ...baseManifest, entries: [{ ...makeEntry('zh'), utteranceSha256: '0'.repeat(64) }, makeEntry('en')] }));
  await badUtterance.ready;
  assert.equal(badUtterance.available('result', 'result-locked', 'zh'), false, 'changed spoken text or role invalidates clip');

  const audio = create(options(baseManifest));
  await audio.ready;
  assert.equal(audio.available('result', 'result-locked', 'zh'), true);
  assert.equal(audio.available('result', 'result-locked', 'en'), true);
  assert.equal((await audio.play('result', 'result-locked', 'zh')).ok, true);
  assert.equal(new URL(FakeAudio.instances.at(-1).src).pathname, '/labs/earthquake/audio/result-result-locked-zh.mp3');
  assert.equal(new URL(FakeAudio.instances.at(-1).src).searchParams.get('v'), 'a'.repeat(64), 'cache identity includes the verified clip hash');
  const first = FakeAudio.instances.at(-1);
  await audio.play('result', 'result-locked', 'en');
  assert.equal(first.paused, true, 'latest play stops previous language');
  assert.equal(new URL(FakeAudio.instances.at(-1).src).pathname, '/labs/earthquake/audio/result-result-locked-en.mp3');
  const newer = create(options({ ...baseManifest, entries: [{ ...makeEntry('zh'), fileSha256: 'b'.repeat(64) }] }));
  await newer.ready;
  await newer.play('result', 'result-locked', 'zh');
  assert.equal(new URL(FakeAudio.instances.at(-1).src).searchParams.get('v'), 'b'.repeat(64), 'regenerated bytes get a new URL even when the pathname is unchanged');
  assert.notEqual(FakeAudio.instances.at(-1).src, first.src);
  newer.dispose();

  let releaseManifest;
  const delayed = create({ ...options(baseManifest), fetcher: async url => {
    if (url === 'content.json') return { ok: true, text: async () => raw };
    return new Promise(resolve => { releaseManifest = () => resolve({ ok: true, text: async () => JSON.stringify(baseManifest) }); });
  } });
  const countBefore = FakeAudio.instances.length;
  const pendingReady = delayed.play('result', 'result-locked', 'zh');
  delayed.stop();
  releaseManifest();
  assert.equal((await pendingReady).reason, 'cancelled', 'stop invalidates a play waiting for manifest verification');
  assert.equal(FakeAudio.instances.length, countBefore, 'cancelled pending request never starts a player');

  FakeAudio.deferred = true;
  const pending = audio.play('result', 'result-locked', 'zh');
  await Promise.resolve();
  const late = FakeAudio.instances.at(-1);
  audio.stop();
  late.resolvePlay();
  assert.equal((await pending).ok, false, 'late play promise cannot restart after stop');
  assert.equal(late.paused, true);
  audio.dispose();
  assert.equal(audio.available('result', 'result-locked', 'zh'), false, 'disposed adapter is inert');
  console.log('Earthquake lab audio adapter: missing, partial, stale, latest-wins, and late-stop PASS');
})().catch(error => { console.error(error); process.exitCode = 1; });
