const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
let pw;try{pw=require('playwright');}catch{pw=require(process.env.PLAYWRIGHT_MODULE||'../../first-batch-books/.qa-deps/node_modules/playwright');}
const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://local').pathname));if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.mp3':'audio/mpeg'})[path.extname(f)]||'application/octet-stream');fs.createReadStream(f).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await pw.chromium.launch({channel:'chrome',headless:true});try{const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const base=`http://127.0.0.1:${server.address().port}/books/moon/`;fs.mkdirSync(path.join(root,'.qa-labs/moon'),{recursive:true});
 for(const width of [320,390,820,1024,1280]){await page.setViewportSize({width,height:844});await page.goto(base);await page.locator('#angle').waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`overflow ${width}`);await page.locator('#language').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`English overflow ${width}`);}
 await page.setViewportSize({width:390,height:844});await page.goto(base);await page.locator('#angle').waitFor();await page.getByRole('button',{name:'下一张 →',exact:true}).click();assert.equal(await page.evaluate(()=>MoonBook.getState().album),1);
 for(const a of [0,45,90,180,270,359]){await page.evaluate(a=>MoonBook.setAngle(a),a);assert.equal(await page.locator('#angle').inputValue(),String(a));}
 await page.getByRole('button',{name:'满月',exact:true}).last().click();await page.getByRole('button',{name:'细月牙',exact:true}).click();await page.getByRole('button',{name:'满月',exact:true}).first().click();
 await page.locator('#diary-shape').selectOption('not-found');await page.locator('#diary-weather').selectOption('cloudy');await page.getByRole('button',{name:'保存这一笔',exact:true}).click();assert.equal(await page.locator('.entries li').count(),1);await page.reload();await page.locator('#angle').waitFor();assert.equal(await page.locator('.entries li').count(),1);assert((await page.locator('.entries').innerText()).includes('没有找到'));
 await page.getByRole('button',{name:'下一张 →',exact:true}).click();
 await page.locator('#album').screenshot({path:path.join(root,'.qa-labs/moon/album-mobile.png')});
 await page.locator('.art img').evaluateAll(xs=>xs.forEach(x=>x.loading='eager'));await page.waitForFunction(()=>Array.from(document.querySelectorAll('.art img')).every(x=>x.complete));const missing=await page.locator('.art img').evaluateAll(xs=>xs.filter(x=>!x.naturalWidth).map(x=>x.src));
 await page.screenshot({path:path.join(root,'.qa-labs/moon/mobile.png'),fullPage:true});await page.setViewportSize({width:1280,height:900});await page.locator('#orbit').screenshot({path:path.join(root,'.qa-labs/moon/lab.png')});assert.deepEqual(errors,[]);assert.deepEqual(missing,[],'All final illustrations must load');console.log('PASS: five responsive widths, both languages, album, phase controls, prediction, diary persistence, images, no JS errors');
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
