const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
let pw;try{pw=require('playwright');}catch{pw=require(process.env.PLAYWRIGHT_MODULE||'../../first-batch-books/.qa-deps/node_modules/playwright');}
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+new URL(req.url,'http://local').pathname);if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');fs.readFile(f,(err,data)=>{if(err){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.webp':'image/webp'})[path.extname(f)]||'application/octet-stream');res.end(data);});});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await pw.chromium.launch({channel:'chrome',headless:true});
 const failures=[];
 async function check(name,run,setup){const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,reducedMotion:'reduce'});const page=await context.newPage();try{if(setup)await setup(page);await page.goto(`http://127.0.0.1:${server.address().port}/books/moon/`);await page.locator('#angle').waitFor();await run(page);console.log('PASS',name);}catch(e){failures.push(name+': '+e.message);console.error('FAIL',name,e.message);}finally{await context.close();}}
 try{
  await check('album keyboard focus survives navigation',async p=>{const b=p.getByRole('button',{name:'下一张 →',exact:true});await b.focus();await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>MoonBook.getState().album),1);assert.equal(await p.evaluate(()=>document.activeElement.textContent),'下一张 →');});
  await check('diary draft survives album and language changes',async p=>{await p.locator('#diary-shape').selectOption('not-observed');await p.locator('#diary-time').fill('17:32');await p.getByRole('button',{name:'下一张 →',exact:true}).click();await p.locator('#language').click();assert.equal(await p.locator('#diary-shape').inputValue(),'not-observed');assert.equal(await p.locator('#diary-time').inputValue(),'17:32');});
  await check('lamp has button alternatives and announced initial value',async p=>{assert(await p.locator('#lamp-angle').getAttribute('aria-valuetext'));const b=p.locator('#lamp-steps button');assert.equal(await b.count(),2);await b.last().tap();assert.equal(await p.locator('#lamp-angle').inputValue(),'105');await p.locator('#lamp-angle').focus();await p.keyboard.press('ArrowLeft');assert.equal(await p.locator('#lamp-angle').inputValue(),'104');assert.equal(await p.evaluate(()=>MoonBook.getState().album),0);});
  await check('reduced motion and zoom preserved',async p=>{assert.equal(await p.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior),'auto');assert(!/user-scalable|maximum-scale/.test(await p.locator('meta[name=viewport]').getAttribute('content')));await p.locator('#angle').focus();await p.keyboard.press('ArrowRight');assert.equal(await p.locator('#angle').inputValue(),'91');assert.notEqual(await p.locator('#angle').evaluate(e=>getComputedStyle(e).outlineStyle),'none');});
  await check('storage refusal remains readable and reports unsaved diary',async p=>{await p.getByRole('button',{name:'保存这一笔',exact:true}).click();assert.equal(await p.locator('.entries li').count(),1);assert((await p.locator('#ending').innerText()).includes('浏览器无法保存'));},p=>p.addInitScript(()=>{Storage.prototype.getItem=()=>{throw Error('blocked');};Storage.prototype.setItem=()=>{throw Error('blocked');};}));
  await check('bad diary records are ignored; valid not-found remains not-found',async p=>{assert.equal(await p.locator('.entries li').count(),1);assert((await p.locator('.entries').innerText()).includes('没有找到'));},p=>p.addInitScript(()=>localStorage.setItem('moon-diary-v1',JSON.stringify([{id:'ok',date:'2026-09-19',time:'17:30',shape:'not-found',weather:'cloudy'},{id:'bad',date:'nonsense',time:'999',shape:'new',weather:'x'},null]))));
  const mock=p=>p.addInitScript(()=>{window.__speech=[];window.__audios=[];window.__cancels=0;window.__mode='reject';Object.defineProperty(window,'speechSynthesis',{value:{speak:u=>__speech.push(u),cancel:()=>{__cancels++;}}});window.SpeechSynthesisUtterance=class{constructor(text){this.text=text;}};window.Audio=class{constructor(src){this.src=src;__audios.push(this);}pause(){this.paused=true;}removeAttribute(){this.src='';}load(){this.cleared=true;}play(){return __mode==='hang'?new Promise(()=>{}):Promise.reject(Error('missing'));}};});
  await check('fallback once, cleanup and stale callback cancellation',async p=>{await p.locator('[data-scene-id=gift] button').click();await p.waitForFunction(()=>__speech.length===1);await p.evaluate(()=>__audios[0].onerror?.());assert.equal(await p.evaluate(()=>__speech.length),1);await p.locator('#stop').click();assert(await p.evaluate(()=>__audios[0].cleared),'failed MP3 must be released after fallback');await p.evaluate(()=>__speech[0].onerror?.());assert.equal(await p.locator('#audio-status').innerText(),'');await p.locator('[data-scene-id=gift] button').click();await p.waitForFunction(()=>__speech.length===2);await p.locator('#language').click();assert.equal(await p.locator('#audio-status').innerText(),'');},mock);
  await check('stalled audio request has bounded fallback',async p=>{await p.clock.install();await p.evaluate(()=>__mode='hang');await p.locator('[data-scene-id=gift] button').click();await p.clock.fastForward(12000);assert.equal(await p.evaluate(()=>__speech.length),1);await p.locator('#stop').click();await p.clock.fastForward(20000);assert.equal(await p.evaluate(()=>__speech.length),1);},mock);
  await check('hidden page and pagehide cancel speech and stale callbacks',async p=>{await p.locator('[data-scene-id=gift] button').click();await p.waitForFunction(()=>__speech.length===1);await p.evaluate(()=>{Object.defineProperty(document,'hidden',{value:true,configurable:true});document.dispatchEvent(new Event('visibilitychange'));__speech[0].onerror?.();});assert.equal(await p.locator('#audio-status').innerText(),'');await p.evaluate(()=>Object.defineProperty(document,'hidden',{value:false,configurable:true}));await p.locator('[data-scene-id=gift] button').click();await p.waitForFunction(()=>__speech.length===2);const count=await p.evaluate(()=>__cancels);await p.evaluate(()=>{dispatchEvent(new Event('pagehide'));__speech[1].onerror?.();});assert((await p.evaluate(()=>__cancels))>count);assert.equal(await p.locator('#audio-status').innerText(),'');},mock);
  await check('diary delete cancel and confirm preserve intended data',async p=>{await p.getByRole('button',{name:'保存这一笔',exact:true}).click();p.once('dialog',d=>d.dismiss());await p.locator('.entries button').click();assert.equal(await p.locator('.entries li').count(),1);p.once('dialog',d=>d.accept());await p.locator('.entries button').click();assert.equal(await p.locator('.entries li').count(),0);await p.reload();await p.locator('#angle').waitFor();assert.equal(await p.locator('.entries li').count(),0);});
 }finally{await browser.close();await new Promise(r=>server.close(r));}
 if(failures.length)throw Error(failures.join('\n'));console.log('PASS all independent Moon interaction regressions (speech mocked; not audio audition or offline proof)');
})().catch(e=>{console.error(e.message);process.exitCode=1;server.close();});
