const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),pw=require(process.env.PLAYWRIGHT_MODULE||'../../first-batch-books/.qa-deps/node_modules/playwright');
const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://local').pathname));if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webp':'image/webp','.mp3':'audio/mpeg'})[path.extname(f)]||'application/octet-stream');fs.createReadStream(f).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await pw.chromium.launch({channel:'chrome',headless:true});try{const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:'+server.address().port;fs.mkdirSync(path.join(root,'.qa-labs/everyday'),{recursive:true});
 for(const book of ['sound','soap']){
  for(const width of [320,390,820,1024,1280]){await page.setViewportSize({width,height:844});await page.goto(base+'/books/'+book+'/');await page.locator(book==='sound'?'#variable':'#next-phase').waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),book+' overflow '+width);await page.locator('#language').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),book+' English overflow '+width);}
  await page.goto(base+'/books/'+book+'/');await page.locator(book==='sound'?'#variable':'#next-phase').waitFor();await page.locator('.art img').evaluateAll(xs=>xs.forEach(x=>x.loading='eager'));await page.waitForFunction(()=>Array.from(document.querySelectorAll('.art img')).every(x=>x.complete));assert.deepEqual(await page.locator('.art img').evaluateAll(xs=>xs.filter(x=>!x.naturalWidth).map(x=>x.src)),[],'all art loads');
  const story=JSON.parse(fs.readFileSync(path.join(root,'books',book,'story.json')));assert.deepEqual(await page.locator('[data-scene-id]').evaluateAll(xs=>xs.map(x=>x.dataset.sceneId)),story.scenes.map(x=>x.id),'story order');
  await page.screenshot({path:path.join(root,'.qa-labs/everyday/'+book+'-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.locator(book==='sound'?'#air .paper':'#compare .paper').screenshot({path:path.join(root,'.qa-labs/everyday/'+book+'-lab-mobile.png')});
 }
 await page.goto(base+'/books/soap/');await page.locator('#next-phase').waitFor();for(const phase of ['detergent','rub','rinse']){await page.locator('#next-phase').click();assert.equal(await page.evaluate(()=>SoapBook.getState().phase),phase);}assert(await page.locator('#next-phase').isDisabled());await page.locator('#foam-slider').fill('18');assert.equal(await page.evaluate(()=>SoapBook.getState().phase),'rinse');await page.getByRole('button',{name:'重新比较',exact:true}).click();assert.equal(await page.evaluate(()=>SoapBook.getState().phase),'water');assert(await page.locator('#foam-slider').isDisabled());
 await page.goto(base+'/books/sound/');await page.locator('#variable').waitFor();assert.equal(await page.evaluate(()=>SoundBook.getState().enabled),false);await page.locator('#variable').fill('1');assert.equal(await page.evaluate(()=>SoundBook.getState().parameters.gain),.018);await page.getByRole('button',{name:'比较轻响',exact:true}).click();await page.locator('#variable').fill('1');assert.equal(await page.evaluate(()=>SoundBook.getState().parameters.frequency),220);await page.locator('#enable-sound').check();await page.getByRole('button',{name:'试听这次设置',exact:true}).click();await page.waitForFunction(()=>SoundBook.getState().activeVoice);await page.locator('#stop').click();assert.equal(await page.evaluate(()=>SoundBook.getState().activeVoice),false);await page.locator('#motion').click();await page.waitForFunction(()=>SoundBook.getState().running);await page.locator('#language').click();assert.equal(await page.evaluate(()=>SoundBook.getState().running),false);await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#motion').click();assert.equal(await page.evaluate(()=>SoundBook.getState().running),false);assert.deepEqual(errors,[]);
 console.log('PASS: five widths, both languages, all illustrations, exact scene order, soap phases/reset/foam, sound variable independence, native WebAudio start/stop, language cleanup, reduced motion. Formal narration not tested.');
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
