// Layout/content contracts, independent of the old slider-based interaction DOM.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),pw=require(process.env.PLAYWRIGHT_MODULE||'../../first-batch-books/.qa-deps/node_modules/playwright');
const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://local').pathname));if(!f.startsWith(root+path.sep))return res.writeHead(403).end();if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webp':'image/webp','.mp3':'audio/mpeg'})[path.extname(f)]||'application/octet-stream');fs.readFile(f,(e,b)=>e?res.writeHead(404).end():res.end(b));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await pw.chromium.launch({channel:'chrome',headless:true});try{const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:'+server.address().port,out=path.join(root,'.qa-labs/everyday');fs.mkdirSync(out,{recursive:true});
for(const book of ['sound','soap']){
 const ready=book==='sound'?'#tap-drum':'#wash-action';
 for(const width of [320,390,820,1024,1280]){await page.setViewportSize({width,height:844});await page.goto(base+'/books/'+book+'/');await page.locator(ready).waitFor();for(const lang of ['zh','en']){if(await page.evaluate(()=>BookUI.lang)!==lang)await page.locator('#language').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),book+' '+lang+' overflow '+width);}}
 await page.goto(base+'/books/'+book+'/');await page.locator(ready).waitFor();await page.locator('.art img').evaluateAll(xs=>xs.forEach(x=>x.loading='eager'));await page.waitForFunction(()=>Array.from(document.querySelectorAll('.art img')).every(x=>x.complete));assert.deepEqual(await page.locator('.art img').evaluateAll(xs=>xs.filter(x=>!x.naturalWidth).map(x=>x.src)),[]);
 const story=JSON.parse(fs.readFileSync(path.join(root,'books',book,'story.json')));assert.deepEqual(await page.locator('[data-scene-id]').evaluateAll(xs=>xs.map(x=>x.dataset.sceneId)),story.scenes.map(x=>x.id));
 await page.screenshot({path:path.join(out,book+'-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.locator(book==='sound'?'#pitch-lab':'#wash-lab').screenshot({path:path.join(out,book+'-lab-mobile.png')});
}
await page.goto(base+'/books/sound/');await page.locator('#tap-drum').waitFor();assert.equal(await page.evaluate(()=>SoundBook.getState().enabled),false);
const parameters={};for(const kind of ['pitch','loudness']){parameters[kind]=[];for(const i of [0,1]){await page.locator(`#${kind}-lab [data-choice="${i}"]`).click();parameters[kind].push(await page.evaluate(()=>SoundBook.getState().lastParameters));}}
assert.equal(parameters.pitch[0].gain,parameters.pitch[1].gain);assert(parameters.pitch[1].frequency>parameters.pitch[0].frequency);assert.equal(parameters.loudness[0].frequency,parameters.loudness[1].frequency);assert(parameters.loudness[1].gain>parameters.loudness[0].gain);assert.deepEqual(errors,[]);
console.log('PASS: five widths, both languages, all story art and scene order, separate A/B parameter independence. Lifecycle/touch/offline covered by qa_interaction_redesign.cjs.');
}finally{await browser.close();server.closeAllConnections();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
