(() => {
 'use strict';
 const U=BookUI,{$,t,el,btn}=U;
 let enabled=false,context=null,voice=null,generation=0,timers=[],raf=0,phase=0,mode='pitch',value=.5,ear=0;
 const period=()=>Math.PI*2/SoundModel.parameters(mode,value).rate;
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 function stopEffects(){generation++;timers.forEach(clearTimeout);timers=[];cancelAnimationFrame(raf);raf=0;if(voice){try{voice.osc.stop();}catch{}voice.osc.disconnect();voice.gain.disconnect();voice=null;}document.querySelectorAll('.vibrating').forEach(n=>n.classList.remove('vibrating'));if($('motion'))$('motion').textContent=t('▶ 连续观察','▶ Watch movement');}
 async function tone(frequency=220,gain=.018,duration=.6){
  const ticket=generation;if(!enabled)return;
  try{if(!context)context=new (window.AudioContext||window.webkitAudioContext)();await context.resume();if(ticket!==generation||!enabled)return;
   if(voice){try{voice.osc.stop();}catch{}voice.osc.disconnect();voice.gain.disconnect();}
   const osc=context.createOscillator(),g=context.createGain(),now=context.currentTime;osc.type='sine';osc.frequency.value=frequency;g.gain.setValueAtTime(0,now);g.gain.linearRampToValueAtTime(Math.min(.03,gain),now+.04);g.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.connect(g);g.connect(context.destination);const current={osc,gain:g};voice=current;osc.onended=()=>{osc.disconnect();g.disconnect();if(voice===current)voice=null;};osc.start(now);osc.stop(now+duration+.02);
  }catch{enabled=false;if($('enable-sound'))$('enable-sound').checked=false;$('audio-status').textContent=t('声音暂不可用，仍可观察画面。','Sound unavailable. You can still watch.');}
 }
 function strike(type){U.stop();const n=$(type);n.classList.add('vibrating');timers.push(setTimeout(()=>n.classList.remove('vibrating'),650));tone(type==='drum'?160:330,.018,.55);}
 function stage(parent){const box=el('div','paper');box.append(el('h3','',t('敲一下，看一看','Tap once. Watch closely.')));const visual=el('div','tone-stage');visual.innerHTML='<div id="drum" class="drum" aria-hidden="true"></div><div id="string" class="string" aria-hidden="true"></div>';box.append(visual);const controls=el('div','controls');controls.append(btn(t('轻敲小鼓','Tap the drum'),()=>strike('drum')),btn(t('拨一下弦','Pluck the string'),()=>strike('string')),btn(t('按住，停下来','Touch and stop'),U.stop));box.append(controls);const label=el('label'),check=el('input');check.id='enable-sound';check.type='checkbox';check.checked=enabled;check.onchange=()=>{U.stop();enabled=check.checked;};label.append(check,document.createTextNode(t('打开轻声试听（先调低设备音量）','Enable gentle sounds (lower device volume first)')));box.append(label,el('p','hint',t('不开声音也能观察。鼓面和弦动起来了吗？','You can watch with sound off. Can you see the drumhead and string move?')));parent.append(box);}
 function draw(){const p=SoundModel.parameters(mode,value);const svg=$('air-svg');if(!svg)return;svg.replaceChildren();const ns='http://www.w3.org/2000/svg';const s=(tag,attrs)=>{const n=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));return n;};
  for(let i=0;i<31;i++){const x=SoundModel.particle(i,phase,p.amplitude,p.rate);svg.append(s('line',{x1:x.equilibrium,y1:45,x2:x.equilibrium,y2:145,stroke:'#c4d3c6','stroke-dasharray':'2 6'}));for(let row=0;row<3;row++)svg.append(s('circle',{cx:x.x,cy:65+row*32,r:i===15&&row===1?7:4,fill:i===15&&row===1?'#bc4c21':'#326c61','data-index':i,'data-equilibrium':x.equilibrium}));}
  $('comparison').textContent=mode==='pitch'?t('只变快慢 · 来回幅度保持一样','Change rate only · movement size stays the same'):t('只变幅度 · 振动快慢保持一样','Change movement size only · rate stays the same');$('variable-label').textContent=mode==='pitch'?t('慢 → 快','Slower → faster'):t('小 → 大','Smaller → larger');$('variable').value=value;$('phase').max=period();$('phase').value=phase;
 }
 function airLab(parent){const box=el('div','paper');box.append(el('h3','',t('盯住橙色粒子，它去了哪里？','Follow the orange particle. Where does it go?')));box.innerHTML+='<svg id="air-svg" class="viz" viewBox="0 0 560 180" role="img"></svg>';$('book');const status=el('p','metric');status.id='comparison';box.append(status);const modes=el('div','controls');[['pitch',t('比较高低','Compare pitch')],['loudness',t('比较轻响','Compare loudness')]].forEach(([id,label])=>{const b=btn(label,()=>{U.stop();mode=id;value=.5;phase=0;box.querySelectorAll('[data-mode]').forEach(n=>n.setAttribute('aria-pressed',String(n.dataset.mode===mode)));draw();});b.dataset.mode=id;b.setAttribute('aria-pressed',String(mode===id));modes.append(b);});box.append(modes);const label=el('label');label.htmlFor='variable';label.id='variable-label';const input=el('input');input.id='variable';input.type='range';input.min=0;input.max=1;input.step=.05;input.oninput=()=>{U.stop();value=Number(input.value);draw();};box.append(label,input);const phaseLabel=el('label','',t('拖动时间，慢慢观察','Move through time and watch slowly'));phaseLabel.htmlFor='phase';const slide=el('input');slide.id='phase';slide.type='range';slide.min=0;slide.max=12.5664;slide.step=.05;slide.value=phase;slide.oninput=()=>{U.stop();phase=Number(slide.value);draw();};box.append(phaseLabel,slide);const controls=el('div','controls'),motion=btn('',()=>{if(raf){U.stop();return;}U.stop();if(reduced.matches){phase=(phase+.4)%period();draw();return;}motion.textContent=t('暂停观察','Pause movement');let previous=performance.now();const frame=now=>{phase=(phase+Math.min(.05,(now-previous)/1000)*2)%period();previous=now;draw();raf=requestAnimationFrame(frame);};raf=requestAnimationFrame(frame);});motion.id='motion';motion.textContent=t('▶ 连续观察','▶ Watch movement');controls.append(btn(t('前进一小步','One small step'),()=>{U.stop();phase=(phase+.35)%period();draw();}),motion,btn(t('试听这次设置','Hear this setting'),()=>{U.stop();const p=SoundModel.parameters(mode,value);tone(p.frequency,p.gain,.7);if(!enabled)$('audio-status').textContent=t('声音未开启；可在小鼓旁打开试听。','Sound is off; enable it beside the drum.');}));box.append(controls,el('p','hint',t('橙色粒子在原来的位置附近来回动，疏密变化向右传。','The orange particle moves back and forth near its starting place. The changing compression travels right.')));const quiz=el('p','',t('会一路跑到右边的是哪一个？','Which one travels all the way to the right?')),feedback=el('p','feedback');feedback.setAttribute('role','status');box.append(quiz,btn(t('橙色粒子','The orange particle'),()=>feedback.textContent=t('看看虚线：橙色粒子会回来。再试一次。','Look at the dotted line: the particle comes back. Try again.')),btn(t('空气疏密的变化','The changing compression'),()=>feedback.textContent=t('对，传过去的是变化！','Yes! The disturbance travels.')),feedback);parent.append(box);$('air-svg').setAttribute('aria-label',t('空气粒子在固定位置附近往复，疏密变化向右传播','Air particles oscillate locally while the compression pattern travels right'));draw();}
 function hearing(parent){const box=el('div','paper');box.append(el('h3','',t('接力到大脑','A relay to the brain')));const names=[['耳道','Ear canal'],['耳膜','Eardrum'],['小骨头','Tiny bones'],['耳蜗','Cochlea'],['听觉神经','Auditory nerve'],['大脑','Brain']];const descriptions=[['声音沿耳道到达耳膜。','Sound passes along the ear canal to the eardrum.'],['薄薄的耳膜跟着振动。','The thin eardrum vibrates.'],['三块小骨头把振动传向内耳。','Three tiny bones pass vibrations toward the inner ear.'],['耳蜗里的液体和结构运动，感觉细胞帮助把振动转为电信号。','Movement in the cochlea stimulates sensory cells that help turn vibrations into electrical signals.'],['这里传递的是电信号，不是沿着神经跑的空气粒子。','Electrical signals travel here, not air particles moving along a nerve.'],['大脑处理这些信号，我们认出了鼓声。','The brain processes these signals, and we recognize the drum.']];const steps=el('div','ear-steps'),out=el('p','metric');out.setAttribute('role','status');const update=()=>{out.textContent=t(...descriptions[ear]);steps.querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===ear)));};names.forEach((name,i)=>steps.append(btn((i+1)+' · '+t(...name),()=>{U.stop();ear=i;update();})));box.append(steps,out,el('p','hint',t('耳道 → 耳膜 → 小骨头 → 耳蜗：振动；耳蜗 → 神经 → 大脑：电信号。','Canal → eardrum → bones → cochlea: vibration. Cochlea → nerve → brain: electrical signals.')));parent.append(box);update();}
 function finale(parent){const box=el('div','paper'),out=el('p','metric',t('轮到你，轮到我。','Your turn. My turn.'));out.id='beat-status';box.append(el('h3','',t('一段四拍的小合奏','A four-beat duet')),btn(t('开始四拍','Start four beats'),()=>{U.stop();const ticket=generation;[0,1,2,3].forEach(i=>timers.push(setTimeout(()=>{if(ticket!==generation)return;out.textContent=(i+1)+' / 4 · '+(i%2?t('松鼠','Squirrel'):t('咚咚','Dongdong'));tone(i%2?330:160,.018,.3);},i*800)));timers.push(setTimeout(()=>{if(ticket===generation)out.textContent=t('合奏结束。让耳朵休息一下。','All done. Give your ears a break.');},3200));}),out);parent.append(box);}
 function render(story){U.begin(story,t('森林声音剧场','The forest sound stage'),t('小鼓响了一声，咚咚想追上它。','One drumbeat. Dongdong wants to follow it.'),[['stage',t('敲一下','Tap')],['air',t('跟着变化走','Follow')],['hearing',t('走进耳朵','Hear')],['finale',t('轮流合奏','Play together')]]);const first=U.section(t('01 · 鼓声藏在哪里？','01 · Where did the drumbeat go?'),'stage');U.scenes(first,['concert','missing','vibration','stop']);stage(first);const air=U.section(t('02 · 传过去的是什么？','02 · What travels?'),'air');U.scenes(air,['air','pitch','loudness']);airLab(air);const earSection=U.section(t('03 · 耳朵里的接力','03 · A relay inside the ear'),'hearing');U.scenes(earSection,['ear','brain']);hearing(earSection);const end=U.section(t('04 · 让朋友舒服地听见','04 · Comfortable listening'),'finale');U.scenes(end,['care','together']);finale(end);U.words(end);U.notes(end,[t('空气动画是一维纵波的慢放模型。粒子、距离、时间和振幅未按真实尺度；虚线标出平衡位置。频率比较保持振幅设置不变，振幅比较保持频率不变。真实感知响度还与频率、距离、环境和听者有关。','The air animation is a slowed one-dimensional longitudinal-wave model, not to scale. Dotted lines mark equilibrium positions. Pitch comparisons hold amplitude fixed; amplitude comparisons hold frequency fixed. Perceived loudness also depends on frequency, distance, surroundings and the listener.'),t('试听为短暂合成纯音，不是鼓或弦的实录，也不能据软件音量推断耳边分贝。初始静音；成人先调低设备音量，不贴耳听，不追求更响。减少动态效果时使用单步观察。','The brief synthesized tones are not recordings of drums or strings. Software gain does not determine sound level at the ear. Sound starts off. A grown-up should lower device volume; do not hold speakers to ears or seek louder sound. Use manual steps with reduced motion.')],[['NIDCD · How Do We Hear?','https://www.nidcd.nih.gov/health/how-do-we-hear'],['NIDCD · How Is Sound Measured?','https://www.nidcd.nih.gov/health/how-sound-measured']]);}
 reduced.addEventListener('change',()=>U.stop());U.mount(render,stopEffects);window.SoundBook={stop:U.stop,getState:()=>({lang:U.lang,mode,value,phase,enabled,activeVoice:!!voice,parameters:SoundModel.parameters(mode,value),running:!!raf})};
})();
