/* Independent story-first book. No fixed-page reader and no synthetic narration. */
window.BOOK={id:'earthquake',audioVer:1};
(()=>{'use strict';const U=EarthquakeUI,N=EarthquakeNavigation,session=U.createSession(),loc=N.parseBookLocation(location.search,location.hash);let lang=loc.lang,content,narrator,audioState='loading',views={},textNodes=[],images=[];
const t=(z,e)=>lang==='en'?e:z;
const bind=(node,fn)=>{textNodes.push(()=>node.textContent=fn());return node;};
function line(id){return content.scenes.find(s=>s.id===id)[lang];}
function spoken(node,kind,id,getText){textNodes.push(()=>U.narratedText(node,getText(),kind,id,lang));return node;}
function scene(parent,ids,image){const section=U.el('section','story-section');ids.forEach(id=>section.append(spoken(U.el('p'),'scene',id,()=>line(id))));if(image){const im=U.el('img','scene-art');im.hidden=true;im.alt='';images.push({image,im});section.prepend(im);}parent.append(section);return section;}
function extension(container,chapter,next){const row=U.el('div','extension'),link=bind(U.el('a','continue'),()=>t('去实验室，换个角度看','Explore another view in the lab')),keep=bind(U.el('a','continue'),()=>t('继续故事 →','Continue the story →')),status=U.el('p','extension-status');status.setAttribute('role','status');keep.href=next;keep.onclick=()=>session.cancel('navigate');link.href=N.buildLabHref(chapter,lang);link.onclick=async e=>{e.preventDefault();const ticket=session.epoch;const ready=navigator.onLine?{ready:false}:await Promise.race([window.KBOfflineLab?.check('earthquake')||Promise.resolve({ready:false}),new Promise(r=>setTimeout(()=>r({ready:false}),2500))]).catch(()=>({ready:false}));if(ticket!==session.epoch)return;if(!N.canEnterLab({online:navigator.onLine,cached:ready.ready})){status.textContent=t('联网后可进入实验室。你仍可继续故事。','Connect to enter the lab. You can still continue the story.');return;}session.cancel('navigate');location.href=N.buildLabHref(chapter,lang);};textNodes.push(()=>{link.href=N.buildLabHref(chapter,lang);status.textContent='';});row.append(link,keep,status);container.append(row);}
function renderLanguage(){document.documentElement.lang=lang==='en'?'en':'zh-CN';document.title=content.title[lang];document.getElementById('language').textContent=lang==='en'?'中文':'English';textNodes.forEach(fn=>fn());Object.values(views).forEach(v=>v.render());renderAudioStatus();}
function mount(data){content=data;const book=document.getElementById('book');book.replaceChildren();book.append(bind(U.el('p','eyebrow'),()=>t('岩岩的博物馆 · 会动的大地','Yan-Yan’s museum · The moving Earth')),bind(U.el('h1'),()=>content.title[lang]));const nav=U.el('nav','chapter-nav');for(const [id,z,e]of [['fault-lab','看看接缝','Watch the fault'],['wave-lab','追踪振动','Follow the wave'],['exhibit-lab','帮忙布展','Arrange the display']]){const a=bind(U.el('a'),()=>t(z,e));a.href='#'+id;a.onclick=()=>session.cancel('navigate');nav.append(a);}book.append(nav);
 scene(book,['invitation','quiet-model'],'opening');scene(book,['stuck'],'observation');const fault=U.el('section','lab');fault.id='fault-lab';book.append(fault);views.fault=mountFault(fault,{content,lang:()=>lang,session});extension(fault,'fault-lab','#after-fault');scene(book,['slip']).id='after-fault';scene(book,['flags'],'arrival');const wave=U.el('section','lab');wave.id='wave-lab';book.append(wave);views.wave=mountWave(wave,{content,lang:()=>lang,session});extension(wave,'wave-lab','#after-wave');scene(book,['little-rock']).id='after-wave';scene(book,['curator'],'exhibit');const exhibit=U.el('section','lab');exhibit.id='exhibit-lab';book.append(exhibit);views.exhibit=mountExhibit(exhibit,{content,lang:()=>lang,session});const skip=bind(U.el('a','continue'),()=>t('直接看开幕 →','Go to opening day →'));skip.href='#ending';skip.onclick=()=>session.cancel('skip');exhibit.append(skip);scene(book,['opening-day']).id='ending';const vocab=U.el('div','vocab');content.vocab.forEach(x=>vocab.append(spoken(U.el('p'),'vocab',x.id,()=>x[lang])));book.append(vocab);const notes=U.el('details','notes');notes.append(bind(U.el('summary'),()=>t('给大人的阅读笔记','Notes for grown-ups')),bind(U.el('p'),()=>content.adultNotes[lang]));book.append(notes);renderLanguage();if(loc.chapter)document.getElementById(loc.chapter).scrollIntoView();
 // Art is registered only once reviewed. Missing art does not become a broken image.
 fetch('art-manifest.json').then(r=>r.ok?r.json():{entries:[]}).then(m=>{for(const {image,im}of images){const asset=m.entries.find(x=>x.id===image&&x.reviewed);if(asset){im.onload=()=>im.hidden=false;im.src=asset.path;im.alt=t('岩岩在博物馆布展','Yan-Yan preparing the museum display');}}}).catch(()=>{});
}
function renderAudioStatus(){const status=document.getElementById('audio-status');status.textContent=audioState==='unavailable'?t('这句暂时听不了，仍可阅读文字。','This audio is unavailable. You can still read the text.'):audioState==='loading'?t('正在准备朗读…','Preparing narration…'):audioState==='playing'?t('正在朗读','Reading aloud'):'';document.getElementById('edition').textContent=t('岩岩的博物馆 · 中英双语点读','Yan-Yan’s museum · Bilingual read-aloud');}
document.addEventListener('click',e=>{const b=e.target.closest('.listen');if(b&&!b.disabled)narrator?.play(b.dataset.kind,b.dataset.itemId,lang);});
document.getElementById('stop').onclick=()=>session.cancel('stop');document.getElementById('language').onclick=()=>{session.cancel('language');lang=lang==='zh'?'en':'zh';history.replaceState(null,'','?lang='+lang+location.hash);renderLanguage();};window.addEventListener('blur',()=>session.cancel('blur'));window.addEventListener('pagehide',()=>session.cancel('pagehide'));window.addEventListener('pageshow',e=>{if(e.persisted)session.cancel('restore');});document.addEventListener('visibilitychange',()=>{if(document.hidden)session.cancel('hidden');});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',()=>session.cancel('motion'));
window.EarthquakeBook={snapshot:()=>({lang,audioState,epoch:session.epoch,...Object.fromEntries(Object.entries(views).map(([k,v])=>[k,v.snapshot()]))}),stop:()=>session.cancel('stop')};fetch('story.json').then(r=>{if(!r.ok)throw Error('story unavailable');return r.text();}).then(async raw=>{mount(JSON.parse(raw));const manifest=await fetch('audio-manifest.json').then(r=>r.ok?r.json():null).catch(()=>null);narrator=EarthquakeAudio.createNarrator({manifest,sourceRaw:raw,session,onStatus:({state})=>{audioState=state;renderAudioStatus();}});await narrator.ready;U.audioAvailable=narrator.available;audioState=[...content.scenes.map(x=>({...x,kind:'scene'})),...content.vocab.map(x=>({...x,kind:'vocab'})),...content.interactions].filter(x=>x.narrationNeeded).every(x=>['zh','en'].every(l=>narrator.available(x.kind,x.id,l)))?'idle':'unavailable';renderLanguage();}).catch(()=>{if(content){audioState='unavailable';renderAudioStatus();return;}document.getElementById('book').textContent='故事暂时无法打开，请稍后重试。 Story unavailable. Please try again.';});})();
