window.mountWave=function(container,{content,lang,session}){
 const {el,button,svg,shape}=EarthquakeUI,W=EarthquakeWave,t=(z,e)=>lang()==='en'?e:z;let state=W.createWave(),flag='a',prediction='watch';
 const heading=el('h2'),graphic=svg(''),result=el('p','result'),positions=el('details','tools'),ps=el('summary'),positionButtons=el('div','controls'),predict=el('details','prediction'),qs=el('summary'),answers=el('div','controls'),controls=el('div','controls'),tools=el('details','tools'),ts=el('summary'),extras=el('div','controls');result.setAttribute('role','status');positions.append(ps,positionButtons);predict.append(qs,answers);tools.append(ts,extras);const local=el('p','local-observation');tools.append(local);
 const a=button('A',()=>{flag='a';render();}),b=button('B',()=>{flag='b';render();});positionButtons.append(a,b);
 for(const slot of ['left','center','right']){const btn=button('',()=>{if(state.phase!=='ready')return;try{state=W.placeFlag(state,flag,slot);}catch{return;}render();});btn.dataset.slot=slot;positionButtons.append(btn);}
 for(const id of ['a','b','together','watch']){const btn=button('',()=>{prediction=id;predict.open=false;render();});btn.dataset.prediction=id;answers.append(btn);}
 function advance(){state=W.stepWave(state,.1);render();}
 function pump(){if(state.phase!=='running')return;advance();if(state.phase==='running')session.schedule(pump,100);}
 const start=button('',()=>{if(state.phase==='done')return;const prior=state;session.cancel('wave-start');state=prior.phase==='ready'||prior.phase==='paused'?W.setWaveMode(prior,'running'):prior;render();if(!matchMedia('(prefers-reduced-motion: reduce)').matches)pump();},'wave-start');
 const step=button('',()=>{const prior=state;session.cancel('wave-step');state=prior.phase==='ready'||prior.phase==='paused'?W.setWaveMode(prior,'running'):prior;advance();if(state.phase==='running')state=W.setWaveMode(state,'paused');render();},'wave-step');
 const pause=button('',()=>{session.cancel('wave-pause');render();},'wave-pause');
 const swap=button('',()=>{session.cancel('wave-swap');state=W.createWave({a:state.flags.b,b:state.flags.a});render();},'wave-swap');
 const reset=button('',()=>{session.cancel('wave-reset');state=W.createWave(state.flags);render();},'wave-reset');
 const near=button('',()=>{state=W.selectPoint(state,'near');render();},'wave-near'),far=button('',()=>{state=W.selectPoint(state,'far');render();},'wave-far');
 controls.append(start,step,pause);extras.append(near,far,swap,reset);container.append(heading,predict,graphic,controls,result,positions,tools);
 function render(){EarthquakeUI.narratedText(local,content.interactions.find(x=>x.id==='local-motion')[lang()],'result','local-motion',lang());EarthquakeUI.narratedText(heading,content.interactions.find(x=>x.id==='wave-predict')[lang()],'prompt','wave-predict',lang());ps.textContent=t('摆放旗子（开始前）','Place flags before starting');ts.textContent=t('追踪与重试','Track and retry');qs.textContent=t('我的猜想：','My prediction: ')+({a:'A',b:'B',together:t('一起','Together'),watch:t('先看看','Just watch')}[prediction]);
  a.setAttribute('aria-pressed',flag==='a');b.setAttribute('aria-pressed',flag==='b');positionButtons.querySelectorAll('[data-slot]').forEach(btn=>{btn.textContent=({left:t('左边','Left'),center:t('中间','Middle'),right:t('右边','Right')})[btn.dataset.slot];btn.disabled=state.phase!=='ready'||state.flags[flag==='a'?'b':'a']===btn.dataset.slot;});answers.querySelectorAll('button').forEach(btn=>btn.textContent=({a:t('A先','A first'),b:t('B先','B first'),together:t('一起','Together'),watch:t('先看看','Just watch')})[btn.dataset.prediction]);
  start.textContent=state.phase==='paused'?t('继续观察','Continue observing'):t('开始观察','Start observing');step.textContent=t('下一小步','Next small step');pause.textContent=t('暂停','Pause');swap.textContent=t('交换两面旗，再试','Swap flags and retry');reset.textContent=t('重新观察','Start again');near.textContent=t('追踪近处小标记','Track the near marker');far.textContent=t('追踪远处小标记','Track the far marker');near.setAttribute('aria-pressed',state.selectedPoint==='near');far.setAttribute('aria-pressed',state.selectedPoint==='far');start.disabled=state.phase==='running'||state.phase==='done';step.disabled=state.phase==='done';pause.disabled=state.phase!=='running';
  const any=state.arrived.a||state.arrived.b,id=any?(Math.abs(state.arrivalTimes.a-state.arrivalTimes.b)<1e-9?'arrived-together':state.arrivalTimes.a<state.arrivalTimes.b?'arrived-a':'arrived-b'):state.time===0?'wave-ready':'wave-moving';EarthquakeUI.narratedText(result,content.interactions.find(x=>x.id===id)[lang()],'result',id,lang());container.dataset.phase=state.phase;
  graphic.setAttribute('aria-label',t('地下震源向外传播波，小标记在原位附近运动，旗子记录到达','A wave spreads from an underground source. Markers move locally; flags record arrival.'));graphic.replaceChildren();shape(graphic,'rect',{x:20,y:60,width:520,height:180,rx:10,fill:'#efd8b0'});shape(graphic,'path',{d:'M20 60H540',stroke:'#73513c','stroke-width':4});shape(graphic,'path',{d:'M355 60L280 200L258.5714285714 240',stroke:'#963e2a','stroke-width':4});
  const cx=280,cy=200,scale=140;shape(graphic,'circle',{cx,cy,r:Math.max(0,state.time*scale),fill:'none',stroke:'#267e83','stroke-width':3,opacity:state.time>0?1:0});shape(graphic,'circle',{cx,cy,r:6,fill:'#963e2a'});shape(graphic,'text',{x:cx+10,y:cy+23,'font-size':14,fill:'#59382a'},t('震源','Focus'));
  for(const f of ['a','b']){const x=cx+W.slots[state.flags[f]]*scale;shape(graphic,'path',{d:`M${x} 60V18h28v22h-28`,stroke:'#29473f',fill:state.arrived[f]?'#f0b842':'#fff8e7','stroke-width':2});shape(graphic,'text',{x:x+8,y:35,'font-size':15,fill:'#29473f'},f.toUpperCase());shape(graphic,'text',{x:x-6,y:53,'text-anchor':'end','font-size':13,fill:'#29473f'},state.arrived[f]?t('到了','Arrived'):'');}
  const p=W.points[state.selectedPoint],x=cx+p.x*scale,y=cy-(p.y+1)*scale;
  shape(graphic,'circle',{cx:x,cy:y,r:12,fill:'none',stroke:'#624726','stroke-dasharray':'3 3'});shape(graphic,'circle',{cx:x+state.particleOffset.x*scale,cy:y-state.particleOffset.y*scale,r:6,fill:'#f4ae32',stroke:'#5e4025','stroke-width':2});
 }
 const off=session.onCancel(()=>{if(state.phase==='running')state=W.setWaveMode(state,'paused');render();});render();return {render,cancel:()=>session.cancel('wave'),destroy:off,snapshot:()=>({...structuredClone(state),prediction})};
};
