/* Little Double Decker — the discoveries that live inside each landmark part.
   Every entry names a region from parts.js, so the studio can gate a discovery to
   the assembly that owns it. Wording follows the picture book; nothing here is a
   measured engineering claim. */
window.DOUBLEDECKER_DETAILS = [
  /* ---- body ---- */
  { id: 'body.shell', region: 'body', name: 'Body shell', zhName: '车身外壳',
    en: 'A red shell of panels bent into a rounded box.', zh: '车身由一块块红色板件折成圆角的方盒。',
    tip: '转动模型，看车身从车头到车尾怎样保持同一个圆角。',
    principle: '车身用薄板包住骨架，既轻又结实。' },
  { id: 'body.windows', region: 'body', name: 'Windows', zhName: '车窗',
    en: 'Two rows of windows, one for each deck.', zh: '两排车窗，上下各占一层。',
    tip: '数一数侧面上下两排各有几扇窗。',
    principle: '车窗让光进来，也方便乘客看风景。' },
  { id: 'body.skirt', region: 'body', name: 'Lower skirt', zhName: '下裙板',
    en: 'The skirt closes the gap between the floor and the road.', zh: '下裙板把地板和路面之间的空隙围起来。',
    tip: '看车身最下面那条深色边，它挡住了底盘。',
    principle: '裙板挡住泥水，也让车身看起来更低更稳。' },
  { id: 'body.livery', region: 'body', name: 'Livery line', zhName: '涂装腰线',
    en: 'A pale line runs the length of the bus.', zh: '一条浅色腰线沿着车身从头跑到尾。',
    tip: '顺着侧面那条浅色线看，它把上下两层分得更清楚。',
    principle: '腰线是涂装，不影响结构，但让车型一眼能认出来。' },

  /* ---- roof ---- */
  { id: 'roof.panel', region: 'roof', name: 'Roof panel', zhName: '车顶板',
    en: 'The panel arches gently over the whole top deck.', zh: '车顶板轻轻拱起，盖住整个上层。',
    tip: '俯视车顶，看它中间比两边略高一点。',
    principle: '微微拱起的车顶更结实，也能排掉雨水。' },
  { id: 'roof.hatch', region: 'roof', name: 'Roof hatch', zhName: '车顶通风口',
    en: 'A small hatch lets air move through the upper deck.', zh: '小小的通风口让空气在上层流动。',
    tip: '在车顶中部找一找那个凸起的小盖。',
    principle: '热空气往上升，从顶部排出去，车内就凉快些。' },
  { id: 'roof.rail', region: 'roof', name: 'Open-top rail', zhName: '敞篷栏杆',
    en: 'On the sightseeing section a rail replaces the roof.', zh: '观光那一段没有车顶，用一圈栏杆围住。',
    tip: '看车尾那截敞开的车顶，边上有一圈栏杆。',
    principle: '去掉车顶并加栏杆，游客就能坐在阳光下看风景。' },

  /* ---- upper deck ---- */
  { id: 'upper.seats', region: 'upper', name: 'Upper seats', zhName: '上层座椅',
    en: 'Rows of soft seats line both sides, facing forward.', zh: '一排排软座分列两边，都朝前坐。',
    tip: '数一数上层一侧有几排座椅。',
    principle: '座椅朝前，急刹车时靠背能挡住乘客往前冲。' },
  { id: 'upper.aisle', region: 'upper', name: 'Walkway', zhName: '上层走道',
    en: 'A clear walkway runs down the middle.', zh: '中间留出一条畅通的走道。',
    tip: '从上层正前方看进去，找到中间那条空道。',
    principle: '走道必须一直空着，乘客才能安全通过。' },
  { id: 'upper.poles', region: 'upper', name: 'Grab poles', zhName: '上层扶手',
    en: 'Yellow poles stand between the seats for standing passengers.', zh: '黄色立柱立在座椅之间，供站立的乘客扶握。',
    tip: '找找那几根从上到下的黄杆。',
    principle: '立杆从车顶撑到地板，既是扶手也是车身的支撑。' },
  { id: 'upper.rail', region: 'upper', name: 'Handrail', zhName: '上层横扶手',
    en: 'A rail runs overhead along both sides.', zh: '两侧头顶各有一条横向扶手。',
    tip: '抬头看上层两边，有一根沿车长方向的横杆。',
    principle: '横杆连着立杆，给站立的乘客多一个抓握点。' },
  { id: 'upper.floor', region: 'upper', name: 'Upper floor', zhName: '上层地板',
    en: 'A strong floor carries the upper deck above the lower one.', zh: '坚固的地板把上层架在下层之上。',
    tip: '拆开上层，看它下面是一整块地板。',
    principle: '地板同时是下层的天花板，一层板干两件事。' },

  /* ---- lower deck ---- */
  { id: 'lower.seats', region: 'lower', name: 'Lower seats', zhName: '下层座椅',
    en: 'The lower deck seats the same way as the upper one.', zh: '下层座椅的排法和上层一样。',
    tip: '比较上下两层的座椅，找出不同的地方。',
    principle: '同一套座椅装两层，工厂造起来更省事。' },
  { id: 'lower.floor', region: 'lower', name: 'Lower floor', zhName: '下层地板',
    en: 'A flat floor at boarding height, low enough to step onto.', zh: '下层地板和上车高度差不多，抬脚就能上。',
    tip: '看车门那一级台阶和地板之间的关系。',
    principle: '地板越低，乘客上下车越省力。' },
  { id: 'lower.stroller', region: 'lower', name: 'Stroller space', zhName: '婴儿车区',
    en: 'A clear space beside the door holds a stroller or a wheelchair.', zh: '车门旁留出一片空地放婴儿车或轮椅。',
    tip: '找找车门旁边那片没有座椅的地方。',
    principle: '空地上没有固定座椅，轮椅才能直接开进来。' },
  { id: 'lower.priority', region: 'lower', name: 'Priority seat', zhName: '爱心座',
    en: 'A special seat is kept for people who need it most.', zh: '留出一排座位给最需要的人。',
    tip: '在靠近车门的位置找找颜色不同的那几个座位。',
    principle: '离车门近、抬脚就能坐下，老人和孕妇最需要。' },

  /* ---- stairs ---- */
  { id: 'stairs.treads', region: 'stairs', name: 'Steps', zhName: '梯级',
    en: 'Step by step, the stairs carry you up to the top deck.', zh: '一级一级，楼梯把你送到上层。',
    tip: '数一数楼梯到底有几级。',
    principle: '梯级高度一致，走起来才不会绊脚。' },
  { id: 'stairs.rail', region: 'stairs', name: 'Stair handrail', zhName: '楼梯扶手',
    en: 'A yellow rail follows the stairs all the way up.', zh: '黄色扶手一路跟着楼梯拐上去。',
    tip: '顺着扶手看，它在转弯的地方跟着弯了。',
    principle: '扶手转弯是为了让手一直有地方扶。' },
  { id: 'stairs.well', region: 'stairs', name: 'Stairwell', zhName: '楼梯间',
    en: 'The opening in the upper floor is the stairwell.', zh: '上层地板上开的那个口就是楼梯间。',
    tip: '从上层往下看，找到楼梯上来的那个洞。',
    principle: '楼梯间的形状要够大，头顶才不会撞到。' },

  /* ---- cab ---- */
  { id: 'cab.wheel', region: 'cab', name: 'Steering wheel', zhName: '方向盘',
    en: 'A big wheel turns the front wheels left and right.', zh: '大方向盘左右转动前轮。',
    tip: '拖到驾驶室正面，看那个圆圆的转向盘。',
    principle: '方向盘转一圈，前轮只转一个小角度，转向更省力。' },
  { id: 'cab.dash', region: 'cab', name: 'Dashboard', zhName: '仪表台',
    en: 'A panel of dials shows speed and other information.', zh: '仪表台上的一排圆表显示车速等信息。',
    tip: '看方向盘后面那排圆形的表。',
    principle: '仪表把机器状态变成司机一眼能看懂的数字。' },
  { id: 'cab.seat', region: 'cab', name: 'Driver seat', zhName: '驾驶座',
    en: 'The driver sits high, with a clear view of the road.', zh: '驾驶座很高，前方路面看得清楚。',
    tip: '比较驾驶座和乘客座椅的高度。',
    principle: '视线越高，车头前方看不见的区域就越小。' },
  { id: 'cab.glass', region: 'cab', name: 'Windscreen', zhName: '前风挡',
    en: 'A large curved glass wraps around the front of the cab.', zh: '一块大弧面玻璃包住驾驶室前方。',
    tip: '从车头看，玻璃在转角的地方是弯的。',
    principle: '玻璃弯过去，司机不用转头也能看到侧面。' },
  { id: 'cab.mirror', region: 'cab', name: 'Mirrors', zhName: '后视镜',
    en: 'Mirrors show the driver what is beside the bus.', zh: '后视镜让司机看见车旁的情况。',
    tip: '找找车头两侧伸出去的那面镜子。',
    principle: '镜子把车身两侧的死角搬到司机眼前。' },

  /* ---- doors ---- */
  { id: 'doors.leaf', region: 'doors', name: 'Door leaves', zhName: '门扇',
    en: 'Two folding leaves meet in the middle of the doorway.', zh: '两片折叠门扇在门洞中间合上。',
    tip: '拖动动作滑杆，看两片门扇怎样折起来。',
    principle: '折门节省空间，车停稳后门才不会撞到站台。' },
  { id: 'doors.glass', region: 'doors', name: 'Door glass', zhName: '门玻璃',
    en: 'A window in each leaf, top and bottom.', zh: '每片门扇上下各有一块玻璃。',
    tip: '看门扇上玻璃被分成几格。',
    principle: '玻璃门让司机从里面就能看到站台上有没有人。' },
  { id: 'doors.step', region: 'doors', name: 'Entry step', zhName: '上车踏板',
    en: 'A wide step sits just inside the doorway.', zh: '门洞里面就是一块宽宽的踏板。',
    tip: '从门洞往下看，找到第一级踏板。',
    principle: '踏板够宽，乘客进门的脚步才稳。' },
  { id: 'doors.emergency', region: 'doors', name: 'Emergency exit', zhName: '紧急出口',
    en: 'A marked panel at the back opens as an extra way out.', zh: '车尾一块带标记的板是额外的出口。',
    tip: '转到底盘后部，找找那块和车身颜色不同的板。',
    principle: '紧急出口必须能从里面打开，而且通道不能堆东西。' },

  /* ---- engine ---- */
  { id: 'engine.block', region: 'engine', name: 'Engine block', zhName: '发动机机体',
    en: 'The block holds the cylinders where fuel burns.', zh: '机体里装着燃烧燃料的气缸。',
    tip: '转到底盘后方，看那台灰褐色的主机体。',
    principle: '燃料在气缸里燃烧膨胀，把热能变成推活塞的力。' },
  { id: 'engine.fan', region: 'engine', name: 'Cooling fan', zhName: '散热风扇',
    en: 'A fan pulls air through the radiator to carry heat away.', zh: '风扇把空气抽过散热器，把热量带走。',
    tip: '看发动机旁边那个带叶片的大圆盘。',
    principle: '发动机不能太热，风扇把热量吹到空气里。' },
  { id: 'engine.pipes', region: 'engine', name: 'Pipes', zhName: '管路',
    en: 'Bent pipes carry fuel and cooling water.', zh: '弯弯的管路输送燃油和冷却水。',
    tip: '看机体上那些拐来拐去的管子。',
    principle: '管路要避开运动的零件，所以常常绕弯走。' },
  { id: 'engine.tank', region: 'engine', name: 'Fuel tank', zhName: '油箱',
    en: 'A metal tank holds the fuel for the engine.', zh: '一个金属箱给发动机存着燃料。',
    tip: '看发动机旁边那个被两道箍带绑住的方箱。',
    principle: '油箱被箍带固定住，颠簸的路面也不会晃动。' },

  /* ---- chassis ---- */
  { id: 'chassis.rail', region: 'chassis', name: 'Chassis rails', zhName: '底盘纵梁',
    en: 'Two long rails run the full length of the bus.', zh: '两根长长的纵梁贯通整个车身。',
    tip: '从下往上看，找到那两根平行的长梁。',
    principle: '纵梁把车身和车轴连成一体，是整车的骨架。' },
  { id: 'chassis.cross', region: 'chassis', name: 'Cross members', zhName: '横撑',
    en: 'Cross members tie the two rails together.', zh: '横撑把两根纵梁连在一起。',
    tip: '数一数两根纵梁之间有几根横撑。',
    principle: '横撑让骨架不会左右扭动，车身才稳。' },
  { id: 'chassis.axle', region: 'chassis', name: 'Axles', zhName: '车轴',
    en: 'Two axles carry the wheels, front and back.', zh: '前后两根车轴把车轮装上去。',
    tip: '看纵梁两端，各有一根横向伸出的轴。',
    principle: '车轴把车身的重量传给车轮，再传给路面。' },

  /* ---- wheels ---- */
  { id: 'wheels.tire', region: 'wheels', name: 'Tire', zhName: '轮胎',
    en: 'Thick black rubber grips the road.', zh: '厚厚的黑色橡胶抓紧路面。',
    tip: '放大车轮，看外圈那层橡胶有多厚。',
    principle: '橡胶有弹性，能把路面的震动吸掉一部分。' },
  { id: 'wheels.tread', region: 'wheels', name: 'Tread', zhName: '轮胎花纹',
    en: 'Grooves in the rubber push water aside.', zh: '橡胶上的沟槽把水挤到两边。',
    tip: '凑近看轮胎表面那一圈花纹。',
    principle: '花纹把积水排走，轮胎才不会在湿路上打滑。' },
  { id: 'wheels.hub', region: 'wheels', name: 'Hubcap', zhName: '轮毂盖',
    en: 'A shiny silver cover sits over the centre of each wheel.', zh: '每个车轮中心盖着一个亮亮的银色圆盖。',
    tip: '看轮胎中间那个银色的圆盘。',
    principle: '轮毂盖挡住灰尘和泥水，保护里面的轴承。' },
  { id: 'wheels.arch', region: 'wheels', name: 'Wheel arch', zhName: '轮罩',
    en: 'A curved arch in the body gives the wheel room to turn.', zh: '车身上弯出一个拱，给车轮留出转动空间。',
    tip: '看车身在车轮上方让出的那个弧形缺口。',
    principle: '转向和颠簸时车轮会摆，轮罩必须比轮胎大一圈。' }
];
